#!/usr/bin/env python3
"""
v2 expansion — fixes every observed misclassification and massively grows all classes.
Run: python3 ml_training/expand_v2.py
"""
import csv, random, os
random.seed(77)

# ─── CORRECTIONS + MAJOR EXPANSIONS ─────────────────────────────────────────
# Keyed on the observed misclassification or thin class.
# Every entry here is a *confirmed correct* label for examples the model got wrong,
# plus large expansions so the model generalises better.

additions: dict[str, list[str]] = {

    # ── FIX 1: "bar" word steals salad/dessert/taco station rows → FoodIconProtein ──
    "FoodIconSalad": [
        "salad bar","fresh salad bar","build your own salad","salad bar station",
        "salad bar line","salad bar options","salad station","tossed salad bar",
        "create your own salad","salad bar buffet","salad buffet","cold salad bar",
        "self serve salad","salad and soup bar","soup and salad bar",
        "salad bar today","house salad bar","dressing bar","salad topping bar",
        "make your own salad","salad bar fresh","farmer's salad bar",
        "fresh greens bar","greens and grains bar","bowl bar salad",
        "antipasto bar","olive bar salad","mediterranean bar salad",
        # more diverse salad entries
        "arugula pear walnut salad","beet goat cheese salad","watermelon feta salad",
        "roasted vegetable salad","grilled peach salad","warm lentil salad",
        "summer corn salad","edamame cucumber salad","mango avocado salad",
        "shaved brussels salad","charred broccoli salad","radicchio salad",
        "blood orange fennel salad","crispy chickpea salad","farro arugula salad",
        "quinoa spinach salad","zucchini ribbon salad","asparagus salad",
        "snap pea salad","radish salad","kohlrabi salad","jicama slaw salad",
        "napa cabbage salad","bok choy salad","endive walnut salad",
        "escarole salad","frisee lardons","lyonnaise salad","salade lyonnaise",
        "composed salad plate","entrée salad","dinner salad large",
        "lunch salad","side salad small","salad cup","salad bowl",
    ],

    "FoodIconCake": [
        "dessert bar","dessert bar station","dessert bar line","sweets bar",
        "dessert station","dessert table","dessert buffet","sweet bar",
        "pastry bar","baked goods bar","dessert bar options","dessert bar menu",
        "dessert bar today","dessert bar selections","holiday dessert bar",
        "dessert bar fresh","dessert bar assorted","dessert bar variety",
        # more cake entries
        "chocolate lava cake","molten chocolate cake","flourless torte",
        "dobos torte","prinsesstårta","battenberg cake","baumkuchen",
        "swiss roll","yule log","buche de noel","profiterole tower",
        "cream puff tower","paris brest","saint honore cake","fraisier",
        "entremet","mousse cake","mirror glaze cake","geode cake",
        "naked cake","semi naked cake","drip cake","pinata cake",
        "fault line cake","gravity defying cake","pull me up cake",
        "number cake","letter cake","character cake","photo cake",
        "ice cream cake","ice cream roll cake","rainbow cake",
        "ombre cake","watercolor cake","marble fondant cake",
    ],

    "FoodIconTaco": [
        "taqueria","taqueria station","taqueria line","taqueria bar",
        "taqueria options","taqueria menu","taqueria fresh","taqueria today",
        "taco bar","taco bar station","taco bar line","taco station",
        "taco line","taco buffet","build your own taco","make your own taco",
        "taco tuesday","taco night","taco truck food","taco stand food",
        "cantina station","cantina line","cantina options","cantina menu",
        "mexican station","mexican bar","mexican food line","fiesta station",
        "tex mex station","tex mex bar","tex mex line","southwest station",
        # more taco entries
        "al pastor street taco","campechano taco","taco dorado","taco frito",
        "taco gobernador","flautas","taquitos","rolled tacos","taquito",
        "dorado taco","crispy taco","hard taco shell","soft corn tortilla taco",
        "double decker taco bell","supreme taco","doritos locos taco",
        "chalupa taco bell","gordita crunch","mexican pizza taco bell",
        "crunchwrap","crunchwrap supreme","mexican crunch wrap",
        "birria consomme taco","red birria taco","quesabirria taco dip",
        "tlayuda oaxacan","memela","tlacoyo","huarache taco",
        "chapulines taco","cricket taco","exotic taco","fusion taco",
        "korean bbq taco","bulgogi taco","teriyaki taco fusion",
    ],

    "FoodIconHotDog": [
        "hot dog station","hot dog bar","hot dog line","hot dog options",
        "hot dog buffet","frank station","frank bar","frank line",
        "hot dog today","hot dog special","hot dog cart","ballpark hot dog",
        "stadium hot dog","state fair corn dog","midway corn dog",
        "corn dog station","corn dog bar","corn dog on a stick",
        "chili dog station","chicago dog line","new york dog line",
        "coney dog station","coney island line","detroit coney",
        "slaw dog","kraut dog","relish dog","mustard dog",
        "everything hot dog","loaded hot dog","gourmet hot dog",
        # more hot dog entries
        "skinless frankfurter","natural casing frank","snap hot dog",
        "all beef hot dog","bun length frank","foot long frank",
        "jumbo hot dog","mini hot dog","cocktail frank","little smokie",
        "pig in a blanket","pigs in blankets","kolache frank",
        "pretzel dog","hot dog pretzel wrapped","pretzel bun dog",
        "waffle dog","pancake wrapped hot dog","french toast dog",
        "bacon wrapped hot dog","danger dog","sonoran bacon wrapped",
        "elote dog","mexican hot dog","chicago style fully loaded",
        "new york style plain","carolina style slaw","kansas city style",
        "texas style chili dog","pacific northwest cream cheese dog",
    ],

    # ── FIX 2: Burrito not matching compound names ──
    "FoodIconBurrito": [
        "beef and bean burrito","beef and bean burritos","bean and beef burrito",
        "beef bean cheese burrito","beef cheese bean burrito",
        "bean cheese beef burrito","carne bean burrito","meat bean burrito",
        "ground beef burrito","seasoned beef burrito","spiced beef burrito",
        "shredded beef burrito","pulled beef burrito","bbq beef burrito",
        "steak and bean burrito","chicken bean burrito","pork bean burrito",
        "black bean burrito","pinto bean burrito","refried bean burrito",
        "bean and cheese quesadilla","bean cheese quesadilla",
        "smothered in sauce burrito","red sauce burrito","green sauce burrito",
        "christmas burrito","half and half burrito","mole burrito",
        "salsa verde burrito","salsa roja burrito","burrito grande",
        "super burrito carne","mission style carne asada","california burrito fries",
        "san diego style burrito","san francisco mission burrito",
        "burrito mojado","wet burrito red","wet burrito green","drenched burrito",
        "burrito platter","burrito combo","burrito meal","burrito bowl style wrap",
        "frozen burrito","el monterey burrito","amy's burrito","trader joes burrito",
        "don miguel burrito","jose ole burrito","delimex burrito",
    ],

    # ── FIX 3: Ice cream sandwich getting cookie ──
    "FoodIconIceCreamSandwich": [
        "lowfat ice cream sandwich","low fat ice cream sandwich",
        "lowfat ice cream sandwiches","low fat ice cream sandwiches",
        "reduced fat ice cream sandwich","light ice cream sandwich",
        "vanilla ice cream sandwich bar","chocolate ice cream sandwich bar",
        "ice cream sandwich bar","ice cream sandwich treat",
        "cookie ice cream sandwich bar","wafer ice cream sandwich",
        "ice cream sandwich cookie","sandwich ice cream bar cookie",
        "frozen ice cream sandwich","packaged ice cream sandwich",
        "individual ice cream sandwich","ice cream sandwich snack",
        "ice cream sandwich dessert","ice cream sandwich treat",
        "chipwich classic","chipwich mini","giant chipwich large",
        "fat free ice cream sandwich","sugar free ice cream sandwich",
        "no sugar added ice cream sandwich","light ice cream bar sandwich",
        "klondike bar ice cream sandwich","snickers ice cream sandwich",
        "twix ice cream sandwich","oreo ice cream sandwich bar",
        "nestle drumstick bar","magnum ice cream bar sandwich",
        "haagen dazs ice cream bar","ben jerrys ice cream sandwich",
        "skinny cow ice cream sandwich","weight watchers ice cream sandwich",
        "enlightened ice cream sandwich","halo top ice cream sandwich",
    ],

    # ── FIX 4: Yogurt → milk (dairy class) ──
    "FoodIconMilk": [
        "yogurt","greek yogurt","plain yogurt","vanilla yogurt","flavored yogurt",
        "low fat yogurt","lowfat yogurt","nonfat yogurt","full fat yogurt",
        "whole milk yogurt","2% yogurt","light yogurt","diet yogurt",
        "salted caramel yogurt","salted caramel remix yogurt","caramel yogurt",
        "strawberry yogurt","blueberry yogurt","peach yogurt","raspberry yogurt",
        "cherry yogurt","lemon yogurt","coconut yogurt","honey yogurt",
        "maple yogurt","coffee yogurt","key lime yogurt","banana yogurt",
        "mixed berry yogurt","tropical yogurt","mango yogurt","pineapple yogurt",
        "chobani yogurt","fage yogurt","siggi's yogurt","noosa yogurt",
        "stonyfield yogurt","nancy's yogurt","wallaby yogurt","brown cow yogurt",
        "dreaming cow yogurt","maple hill yogurt","straus yogurt",
        "skyr","icelandic yogurt","icelandic provisions yogurt","siggi skyr",
        "kefir plain","kefir flavored","drinkable yogurt","danimals yogurt",
        "yoplait yogurt","dannon yogurt","activia yogurt","light and fit",
        "oikos yogurt","oikos pro yogurt","two good yogurt","ratio protein yogurt",
        "triple zero yogurt","protein yogurt","high protein yogurt",
        "yogurt parfait base","yogurt cup","yogurt bowl","yogurt snack",
        "cottage cheese","low fat cottage cheese","small curd cottage cheese",
        "large curd cottage cheese","creamed cottage cheese","daisy cottage cheese",
        "friendship cottage cheese","breakstone cottage cheese",
        "cream cheese","whipped cream cheese","regular cream cheese",
        "ricotta cheese","ricotta whole milk","part skim ricotta",
        "sour cream","light sour cream","reduced fat sour cream","creme fraiche",
        "dairy dessert","dairy snack","dairy product","milk product",
    ],

    # ── FIX 5: Lightly breaded chicken strips / sweet chili chicken → FoodIconChicken ──
    "FoodIconChicken": [
        "lightly breaded chicken strips","lightly breaded chicken breast strips",
        "lightly breaded chicken tenders","lightly breaded chicken",
        "breaded chicken strips","breaded chicken tenders","breaded chicken nuggets",
        "sweet chili chicken","sweet chili glazed chicken","thai sweet chili chicken",
        "sweet and spicy chicken","honey sriracha chicken","sriracha honey chicken",
        "buffalo chicken strips","buffalo chicken tenders","buffalo chicken nuggets",
        "chicken and waffles","chicken n waffles","fried chicken and waffle",
        "nashville hot chicken","spicy fried chicken","hot fried chicken",
        "southern fried chicken pieces","pan fried chicken breast","pan seared breast",
        "air fried chicken breast","air fryer chicken tenders","air fryer nuggets",
        "baked chicken breast meal","oven baked chicken breast","herb baked chicken",
        "lemon herb chicken breast","garlic chicken breast","tuscan chicken",
        "florentine chicken","piccata chicken","francese chicken","marsala chicken",
        "chicken with sauce","sauced chicken breast","glazed chicken piece",
        "teriyaki glazed chicken","honey garlic chicken","bbq chicken piece",
        "chipotle chicken","smoky chicken","cajun chicken piece","blackened chicken",
        "chicken steak","chicken filet","chicken cutlet breaded","chicken milanese",
        "chicken sandwich fillet","crispy chicken fillet","grilled chicken fillet",
        "grilled chicken sandwich","crispy chicken sandwich","spicy chicken sandwich",
        "popcorn chicken box","popcorn chicken meal","chicken bites","dino nuggets",
        "dino chicken nuggets","shaped chicken nuggets","fun shaped nuggets",
        "mcdonalds mcnuggets","chick fil a nuggets","wendy's nuggets",
        "tyson chicken strips","perdue chicken tenders","bell and evans strips",
        "just bare chicken nuggets","applegate chicken nuggets","organic nuggets",
        "frozen chicken strips","frozen chicken tenders","frozen chicken nuggets",
        "chicken meal","chicken entree","chicken plate","chicken dish",
        "wingstop boneless","buffalo wild wings boneless","boneless chicken wingstop",
        "chicken street tacos","chicken tacos","chicken burrito filling",
        "kung pao chicken","moo goo gai pan chicken","chinese chicken dish",
        "chicken fried steak","chicken fried chicken","country fried chicken",
        "chicken parm baked","chicken parmesan baked","chicken cordon bleu",
        "chicken kiev","chicken saltimbocca","stuffed chicken breast",
        "smoked chicken breast","smoked chicken thigh","smoked chicken wings",
        "pellet grill chicken","pit smoked chicken","whole smoked chicken",
    ],

    # ── FIX 6: Ginger sesame seaweed → sushi ──
    "FoodIconSushi": [
        "seaweed","seaweed snack","roasted seaweed","dried seaweed","seaweed sheet",
        "seaweed sheets","nori","nori sheet","nori snack","nori seaweed",
        "toasted nori","seasoned nori","nori crisps","nori chips",
        "ginger sesame seaweed","sesame seaweed snack","sesame nori",
        "wasabi seaweed snack","spicy seaweed snack","flavored seaweed",
        "seaweed salad","wakame salad","wakame seaweed","hijiki salad",
        "kelp noodles","sea vegetable","sea vegetables","ocean vegetable",
        "gimme seaweed","annie chuns seaweed","crispy seaweed","tao kae noi",
        "j&b snacks seaweed","organic roasted seaweed","sea snax",
        # more sushi entries
        "dragon roll sushi","spider roll crab","tempura roll shrimp",
        "baked sushi roll","oven baked sushi","sushi bake dish",
        "crunch roll","crunchy salmon roll","ebi tempura roll",
        "vegetable roll","avocado roll","cucumber roll","asparagus roll",
        "tofu roll vegan sushi","mushroom roll vegan","carrot roll sushi",
        "inari sushi","tofu pouch sushi","inari age","cone sushi",
        "gunkan maki","battleship sushi","ikura gunkan","masago gunkan",
        "chirashi don","chirashi bowl mixed","kaisendon","seafood rice bowl sushi",
        "sashimi platter","sashimi set","omakase sashimi","premium sashimi",
        "hamachi yellowtail sashimi","kanpachi sashimi","madai sashimi",
        "sake salmon sashimi","maguro tuna sashimi","tako octopus sashimi",
        "hotate scallop sashimi","ika squid sashimi","ebi shrimp sashimi",
        "unagi eel sashimi","anago conger eel","saba mackerel sashimi",
        "tai red snapper sashimi","hirame flounder sashimi",
    ],

    # ── FIX 7: Chipotle BBQ Beef / BBQ beef → FoodIconBeef ──
    "FoodIconBeef": [
        "chipotle bbq beef","chipotle beef","chipotle style beef","bbq beef",
        "smoked beef","bbq beef brisket","beef bbq plate","texas bbq beef",
        "carolina bbq beef","kansas city bbq beef","memphis bbq beef",
        "beef station","beef line","beef bar","beef carving station",
        "carving station beef","roast beef station","roast beef carving",
        "prime rib station","prime rib carving","beef entree station",
        "slow roasted beef","slow smoked beef","low and slow beef",
        "beef bulgogi station","korean beef station","japanese beef station",
        "beef teriyaki bowl","beef teriyaki plate","yakiniku beef",
        "philly cheesesteak beef","cheesesteak beef filling","steak sandwich filling",
        "beef kabob","beef kebab skewer","beef satay","beef souvlaki",
        "beef shawarma","beef shawarma plate","beef gyro","beef doner",
        "beef taco filling","carne asada tacos beef","birria beef",
        "birria de res","barbacoa beef","shredded beef barbacoa",
        "suadero beef","beef picadillo hash","ground beef taco",
        "beef ragu sauce","bolognese beef sauce","beef marinara","beef lasagna filling",
        "beef and broccoli stir fry","mongolian beef stir fry","pepper steak",
        "beef with vegetables","beef fried rice","beef lo mein noodle",
        "gyudon beef bowl","beef donburi","beef rice bowl japanese",
        "japanese curry beef","katsu curry beef","beef curry plate",
        "beef pho broth","beef noodle soup taiwanese","lanzhou beef noodle",
        "roast beef au jus","french dip beef","beef dip sandwich filling",
        "beef wellington slice","beef tenderloin roasted","chateaubriand",
        "beef medallion","beef tournedos","beef roulade","stuffed beef",
    ],

    # ── FIX 8: Taqueria / station names → FoodIconTaco (already added above) ──

    # ── FIX 9: "Chicken and Waffles" should not go to utensils ──
    # Already added to FoodIconChicken above

    # ── FIX 10: Fresh fruit → FoodIconApple ──
    "FoodIconApple": [
        "fresh fruit","fresh fruit station","fruit bar","fruit station",
        "fresh fruit bar","fruit selection","seasonal fruit","fresh seasonal fruit",
        "fresh cut fruit","whole fruit","daily fresh fruit","fresh fruit bowl",
        "fruit salad","mixed fruit","fruit mix","fruit medley","tropical fruit mix",
        "fresh fruit cup","fruit cup","melon cup","berry cup","citrus cup",
        "fruit platter","fruit tray","fruit display","fruit arrangement",
        "fruit dessert","fruit snack","fresh fruit snack","healthy fruit snack",
        "fruit option","fruit choice","fruit side","fruit serving",
        "orchard fruit","farm fresh fruit","picked fruit","ripe fruit",
        "assorted fruit","variety fruit","fruit variety","mixed fresh fruit",
        # more apple entries
        "caramel apple dip","apple dipping sauce","apple slices snack pack",
        "sliced apples kids","apple wedge snack","apple coins","apple sticks",
        "dried apple rings","apple fruit leather","apple fruit strip",
        "baked cinnamon apple","glazed apple","poached apple","roasted apple",
        "apple chutney","apple relish","apple mostarda","pickled apple",
        "apple slaw","apple walnut salad","apple grape salad","apple cranberry",
        "apple pear salad","waldorf salad","waldorf apple","classic waldorf",
    ],

    # ── FIX 11: "Drizzilicious Cookies & Cream" → cookie (not candy) ──
    "FoodIconCookie": [
        "drizzilicious","drizzilicious cookies and cream","drizzilicious cookie thins",
        "cookies and cream cookie","cookies n cream cookie","oreo style cookie",
        "cream filled cookie","filled cookie sandwich","creme cookie",
        "chocolate creme cookie","vanilla creme cookie","double stuffed",
        "drizzle cookie","iced drizzle cookie","frosted drizzle cookie",
        "cookie thins","thin crispy cookie","wafer thin cookie","lace cookie",
        "florentine cookie","tuile cookie","cookie bark","chocolate cookie bark",
        "cookies and cream bark","oreo bark","crushed cookie bark",
        "cookies and cream anything","cookies and cream flavored snack",
        "cookies and cream protein bar snack","cookies and cream rice crispy",
        "cookies and cream popcorn","cookies and cream pretzel",
        "cookies and cream brittle","cookies and cream fudge",
        "sandwich cookie assorted","assorted cookie pack","cookie sampler",
        "cookie box","cookie gift box","assorted bakery cookies",
        "soft baked cookie","chewy cookie","crunchy cookie","crispy cookie",
        "homestyle cookie","bakery style cookie","gourmet cookie","artisan cookie",
        "gluten free cookie","vegan cookie","keto cookie","protein cookie",
        "lenny and larry complete cookie","ennies cookie","partake cookie",
        "enjoy life cookie","simple mills cookie","nuttzo cookie",
    ],

    # ── MAJOR EXPANSIONS for accuracy on all underpowered classes ──

    "FoodIconMartini": [
        "vodka soda","rum and diet coke","gin and soda","tequila soda","whiskey soda",
        "bourbon neat","whiskey neat","scotch neat","rye whiskey","bourbon on rocks",
        "whiskey on the rocks","scotch on the rocks","brandy","cognac","armagnac",
        "hennessy","remy martin","patron tequila drink","don julio tequila drink",
        "casamigos drink","clase azul drink","cincoro drink","volcan tequila",
        "vodka cranberry","cape cod drink","bay breeze","madras","sea breeze",
        "amaretto sour cocktail","alabama slammer","fuzzy navel","sex on beach",
        "tequila sunrise cocktail","harvey wallbanger","jungle juice",
        "white russian","black russian","colorado bulldog","kahlua drink",
        "espresso martini shot","pornstar martini shot","french martini",
        "lychee martini","elderflower cocktail","st germain cocktail",
        "aperol aperitivo","campari and soda","negroni sbagliato","americano cocktail",
        "boulevardier whiskey","vieux carre","sazerac","corpse reviver",
        "bee's knees","aviation cocktail","french 75","gold rush cocktail",
        "brown derby","toronto cocktail","black manhattan","perfect manhattan",
        "dry manhattan","sweet manhattan","extra dry martini","bone dry martini",
        "filthy martini","gibson martini","vesper martini","fifty fifty martini",
        "reverse martini","rum sour","pisco sour","amaretto stone sour",
        "new york sour","boston sour","new england sour","paper plane",
        "jungle bird","naked and famous","trinidad sour","oaxacan old fashioned",
        "mezcal negroni","mezcal margarita","spicy mezcal","mezcal sour",
    ],

    "FoodIconVegan": [
        "plant based burger","impossible whopper","beyond meat burger",
        "plant based chicken","impossible chicken","lightlife chicken",
        "vegan wings","cauliflower wings","vegan buffalo wings",
        "mushroom based protein","mushroom meat","shroom burger",
        "lentil protein","lentil loaf","lentil patty","lentil burger",
        "chickpea protein","chickpea patty","chickpea burger","falafel patty",
        "hemp tofu","pea protein tofu","soy free vegan protein",
        "whole food vegan","whole food plant based","wfpb meal",
        "raw vegan dish","raw plant food","living food dish",
        "sprout dish","sprouted grain dish","sprouted lentil dish",
        "nutritional yeast dish","nooch dish","vegan cheese dish",
        "cashew cheese dish","macadamia cheese","almond cheese vegan",
        "vegan mayo","veganaise","just mayo vegan","follow your heart",
        "daiya vegan","violife vegan cheese","miyoko's vegan","kite hill vegan",
        "good planet vegan","treeline vegan","nuts for cheese",
        "vegetable entree","vegetable main","vegetable protein",
        "meatless main","meat free main","plant protein main",
        "veggie burger","garden burger","morningstar burger",
        "boca burger","amy's veggie burger","dr praeger","hilary's burger",
        "sweet earth burger","gardein burger","trader joes veggie",
        "whole foods vegan entree","purple carrot meal","green chef vegan",
        "sun basket vegan","daily harvest vegan","veestro meal",
    ],

    "FoodIconCoffee": [
        "cold brew concentrate","cold brew bottle","bottled cold brew",
        "nitro cold brew can","canned nitro cold brew","starbucks can",
        "starbucks frappuccino bottle","starbucks doubleshot","doubleshot espresso",
        "starbucks refresher","green tea refresher","pink drink starbucks",
        "dragon drink starbucks","mango dragonfruit","strawberry acai",
        "violet drink","medicine ball tea starbucks","honey citrus mint",
        "cafe bustelo","cafe la llave","pilon coffee","cuban espresso shot",
        "colada coffee","cortadito","cafe con leche cuban","cacao coffee",
        "maca coffee","mushroom coffee","four sigmatic","ryze mushroom coffee",
        "chicory coffee","new orleans coffee","cafe du monde","beignet coffee",
        "cowboy coffee","percolator coffee","french press coffee","aeropress",
        "siphon coffee","moka pot coffee","stovetop espresso","bialetti",
        "v60 pour over","chemex pour over","kalita wave","hario pour over",
        "filter coffee","brewed coffee","drip coffee maker","automatic drip",
        "keurig pod coffee","nespresso pod","pod coffee","capsule coffee",
        "instant coffee","nescafe instant","folgers instant","maxwell house",
        "3 in 1 coffee","2 in 1 coffee","white coffee mix","kopiko candy coffee",
        "coffee candy","coffee flavored","coffee dessert","tiramisu coffee",
        "coffee ice cream","coffee gelato","coffee macaron","coffee cake coffee",
    ],

    "FoodIconSoup": [
        "oxtail soup","ox tail broth","beef oxtail stew","oxtail jamaican",
        "jamaican beef soup","caribbean soup","callaloo soup","pepper pot soup",
        "groundnut soup","peanut soup african","egusi soup","ogbono soup",
        "suya soup","jollof inspired soup","groundnut stew",
        "harira soup moroccan","chorba soup","shakshuka tomato base",
        "avgolemono greek","avgolemono chicken rice","giouvetsi soup",
        "fasolada greek bean soup","revithia chickpea soup","tarator cold",
        "gazpacho andaluz","salmorejo cordobes","ajo blanco","ajoblanco",
        "ribollita tuscan","pasta e ceci","pasta e fagioli","acquacotta",
        "minestra soup","zuppa toscana","tuscan white bean soup","ribollita",
        "zurek polish sour rye","barszcz beet soup","żurek soup","zurek",
        "bigos hunter stew","kapusniak cabbage soup","flaki tripe soup",
        "knedlíkový soup czech","goulash soup czech","bramboračka potato",
        "bryndzové halušky broth","sour cherry soup hungarian","meggyleves",
        "gulyás soup","halászlé fisherman","paprikás sauce base soup",
        "caldo verde portuguese","açorda bread soup","sopa alentejana",
        "caldo gallego","fabada asturiana","cocido madrileño","puchero",
        "sinigang soup filipino","tinola chicken soup","nilaga beef soup",
        "bulalo beef marrow","kare kare peanut","soto ayam indonesian",
        "bakso meatball soup","rawon beef soup","sup iga ribs soup",
        "laksa curry noodle soup","bak kut teh","pork rib herb soup",
        "yong tau foo soup","teochew fish soup","fish head curry soup",
    ],

    "FoodIconRamen": [
        "shin ramyeon spicy","ottogi ramyeon","samyang fire noodle",
        "nongshim neoguri","neoguri udon seafood","chapagetti","jjapaghetti",
        "paldo bibimmyeon","paldo bibim noodle","cold bibim noodle",
        "cold buckwheat noodle","naengmyeon","mul naengmyeon","bibim naengmyeon",
        "soba cold dipping","zaru soba cold dipping","mori soba","kake soba warm",
        "tempura soba hot","kitsune soba","tanuki soba","tororo soba",
        "hatena soba","chicken udon hot","nabeyaki udon hot pot","yaki udon",
        "kare udon","tanuki udon","tororo udon","mentsuyu udon",
        "wonton noodle soup cantonese","wonton noodle hong kong","dry wonton noodle",
        "beef brisket noodle hong kong","fish ball noodle","char siu noodle",
        "beef tendon noodle","mixed noodle bowl","combination noodle",
        "thai boat noodle","kuay tiao ruea","boat noodles thai",
        "vietnamese bun bo hue","bun bo hue spicy lemongrass","hue noodle",
        "bun rieu crab noodle","bun mam fermented fish noodle",
        "cao lau noodle hoi an","mi quang turmeric noodle","banh canh noodle",
        "jajangmyeon black bean noodle","jjampong spicy seafood noodle",
        "janchi guksu banquet noodle","kalguksu knife cut noodle",
        "sujebi hand torn noodle","ramyeon soup korean","budae jjigae noodle",
        "army stew with noodles","ramyeon army stew","instant noodle soup",
    ],

    "FoodIconPasta": [
        "cacio e pepe classic","bucatini all amatriciana","penne arrabbiata",
        "spaghetti aglio olio","tonnarelli carbonara","rigatoni amatriciana",
        "tagliatelle ragu","pappardelle wild boar","maltagliati duck ragu",
        "paccheri seafood","bigoli sardine","trofie pesto genovese",
        "trenette pesto","mandilli di seta pesto","trenette al pesto",
        "pizzoccheri buckwheat","sciatt buckwheat fritters","bresaola pasta",
        "casarecce siciliana","pasta alla norma","caponata pasta",
        "pasta con le sarde","busiate trapanese","pasta alla trapanese",
        "orecchiette cime di rapa","strascinate lamb ragu","lampascioni pasta",
        "scialatielli seafood","paccheri lobster","spaghetti vongole",
        "linguine alle vongole","bavette clam sauce","linguine bottarga",
        "pasta bottarga","cuttlefish ink pasta","squid ink spaghetti",
        "squid ink pasta","nero di seppia pasta","black pasta seafood",
        "pasta primavera spring","pasta verdure","vegetable pasta medley",
        "creamy mushroom pasta","wild mushroom pasta","truffle pasta mushroom",
        "porcini pasta","chanterelle pasta","morel pasta","black truffle pasta",
        "lemon pasta","lemon caper pasta","lemon ricotta pasta","lemon zucchini pasta",
        "tomato basil pasta","fresh tomato pasta","raw tomato pasta","panzanella pasta",
        "pesto pasta cold","pasta salad pesto","italian pasta salad cold",
        "pasta e piselli","pasta with peas","pasta con piselli","pasta broccoli",
    ],

    "FoodIconPizza": [
        "pizza station","pizza line","pizza bar","build your own pizza",
        "make your own pizza","pizza buffet","pizza today","daily pizza",
        "pizza special","featured pizza","pizza of the day","pizza night",
        "grandma pizza","sicilian style pizza","roman pizza al taglio",
        "pinsa romana","pizza al taglio slice","pizza bianca rome",
        "focaccia pizza style","schiacciata pizza","pissaladiere",
        "tarte flambee","flammkuchen","german pizza flammkuchen",
        "thai chicken pizza pf changs","bbq chicken pizza california",
        "california pizza kitchen cpk","cpk pizza","cpk style",
        "artichoke pizza nyc","artichoke slice","grandpa pizza",
        "old forge pizza pa","bar pie pizza","tavern cut pizza",
        "thin tavern pizza","cracker thin pizza","ultra thin crust",
        "cast iron pizza","detroit style pan","grandma pan pizza",
        "focaccia topped pizza","olive oil pizza","no sauce pizza",
        "white clam pizza new haven","apizza new haven","wooster street",
        "frank pepe pizza","sally's apizza","modern apizza",
        "pequod's chicago","lou malnati's chicago","giordano's deep dish",
        "connie's pizza","gino's east","chicago style pie",
        "motor city pizza","buddy's pizza detroit","shield's pizza detroit",
        "hungry howie's flavored crust","jet's pizza square","round table pizza",
        "papa murphys take and bake","mod pizza custom","blaze pizza custom",
    ],

    "FoodIconSandwich": [
        "sandwich station","sandwich bar","sandwich line","sandwich buffet",
        "build your own sandwich","make your own sandwich","deli line",
        "deli station","deli bar","cold cuts station","deli sandwich bar",
        "sub station","sub bar","sub line","hoagie station","hoagie bar",
        "grinder station","hero station","hero bar","roll station",
        "deli roll station","deli sandwich fresh","fresh made sandwich",
        "pressed panini station","panini station","panini bar","panini line",
        "melt station","grill station melt","grilled sandwich station",
        "cheesesteak station","philly station","philly bar",
        "french dip station","au jus sandwich station","beef dip station",
        "lobster roll station","seafood roll station","roll station seafood",
        "birria sandwich","torta station","torta bar","cemita station",
        "bánh mì station","banh mi bar","vietnamese sandwich station",
        "smash burger sandwich","burger smash patty","double smash sandwich",
        "chicken sandwich spicy","spicy chicken sandwich station",
        "fish sandwich","filet o fish","fish filet sandwich","mahi sandwich",
        "veggie sandwich","vegetarian sandwich","hummus wrap sandwich",
        "eggplant sandwich","portobello sandwich","mushroom melt",
        "turkey avocado sandwich","blt sandwich classic","club classic",
        "italian combo sub","italian sub loaded","meatball sub","meatball hero",
    ],

    "FoodIconBeer": [
        "craft beer can","craft beer bottle","local beer","local craft beer",
        "tap beer","draft beer tap","keg beer","growler beer","crowler beer",
        "flight of beer","beer flight","beer sampler","beer tasting",
        "pint beer glass","pint of draft","half pint beer","snifter beer",
        "tulip glass beer","goblet beer","weizen glass","boot beer das boot",
        "beer cocktail","shandy","beer and lemonade","radler","beergarita",
        "chelada","michelada","bloody mary beer","beer bloody mary",
        "hard kombucha","jun kombucha alcoholic","jun hard tea",
        "hard tea","twisted tea","truly hard tea","arizona hard tea",
        "spiked lemonade","mikes hard lemonade","truly lemonade","high noon",
        "surfside iced tea vodka","fishers island lemonade",
        "ranch water topo chico","ranch water drink","sparkling ranch water",
        "modelo especial","modelo negra","pacifico beer","sol beer",
        "tecate beer","carta blanca","bohemia beer","victoria beer",
        "negra modelo","corona extra","corona light","corona familiar",
        "super bock beer","sagres beer","imperial beer costa rica",
        "baltica beer","efes beer","tusker beer","castle beer","kingfisher",
        "asahi beer","sapporo beer","kirin beer","suntory beer","hitachino",
        "singha beer","chang beer","leo beer thai","beerlao","tiger beer",
        "tsingtao beer","snow beer","yanjing beer","tsingtao draft",
    ],

    "FoodIconWrap": [
        "wrap station","wrap bar","wrap line","build your own wrap",
        "make your own wrap","wrap buffet","wrap today","fresh wrap",
        "rotisserie wrap","grilled wrap","warm wrap","cold wrap",
        "lavash wrap station","pita station","pita bar","pita line",
        "mediterranean station","mediterranean bar","mediterranean wrap line",
        "middle eastern station","middle eastern bar","falafel station",
        "gyro station","gyro bar","gyro line","gyro cart","gyro truck",
        "shawarma station","shawarma bar","shawarma line","shawarma cart",
        "kebab station","kebab bar","kebab line","souvlaki station",
        "burrito bowl (wrap version)","grain wrap","quinoa wrap","farro wrap",
        "lettuce cup wrap","bibb lettuce wrap","boston lettuce cup",
        "collard green wrap","swiss chard wrap","nori wrap",
        "rice paper roll fresh","fresh roll rice paper","summer roll fresh",
        "crystal roll","transparent roll rice paper","fresh spring roll rice paper",
        "vietnamese summer roll station","fresh roll station","rice paper station",
    ],

    "FoodIconNut": [
        "almond pack","single serve almonds","snack size almonds","grab bag almonds",
        "100 calorie almond pack","individual nut pack","travel nut snack",
        "honey roasted cashews","cinnamon cashews","spiced cashews","coconut cashews",
        "chocolate covered almonds","dark chocolate almonds","milk chocolate almonds",
        "yogurt covered almonds","yogurt covered raisins","chocolate covered cashews",
        "praline pecans","candied pecans","glazed pecans","sugared pecans",
        "cinnamon pecans","spiced walnuts","candied walnuts","maple walnuts",
        "tamari almonds","smokehouse almonds","habanero almonds","wasabi almonds",
        "sea salt almonds","sea salt cashews","sea salt peanuts","lightly salted",
        "dry roasted peanuts","oil roasted peanuts","honey roasted peanuts",
        "spanish peanuts","boiled peanuts southern","kettle roasted peanuts",
        "peanut butter peanuts","chili lime peanuts","tajin peanuts",
        "pistachios shelled","pistachios in shell","roasted pistachios",
        "chili roasted pistachios","honey roasted pistachios",
        "macadamia roasted","macadamia chocolate","kona macadamia","hawaii mac nut",
        "brazil nut raw","brazil nut chocolate","brazil nut snack",
        "hazelnut roasted","hazelnut chocolate","nutella nut base",
        "pine nut toasted","pine nut pesto ingredient","pine nut salad topping",
        "chestnut roasted","roasted chestnuts street","marron glace",
        "mixed nut butter","sunflower seed butter","tahini sesame","tahini sauce",
        "hemp seed snack","pumpkin seed snack","pepitas roasted","chia seed snack",
        "flax seed snack","sunflower seeds","roasted sunflower","baked sunflower",
    ],

    "FoodIconFish": [
        "fish station","fish line","fish bar","fish and seafood station",
        "seafood station","seafood bar","seafood buffet","seafood line",
        "fish fry station","fish fry line","fish fry friday","friday fish fry",
        "fish of the day","catch of the day","daily catch","fresh catch",
        "market fish","fresh fish","fish counter","fish monger",
        "blackened redfish","cajun redfish","redfish on the half shell",
        "striped bass fillet","black sea bass fillet","bronzino whole",
        "porgy fish","scup fish","weakfish","drum fish","croaker fish",
        "wahoo steak","mahi mahi fillet","mahi taco fish","mahi sandwich fish",
        "opah moonfish","escolar white tuna","ono wahoo hawaii","opakapaka",
        "ulua jack fish","kampachi hawaii","onaga red snapper hawaii",
        "hamachi yellowtail fillet","yellowtail collar kama","collar fish",
        "amberjack fillet","kingfish fillet","cobia fillet","tripletail",
        "tilapia fillet baked","tilapia fillet fried","tilapia plate","tilapia meal",
        "swai fillet","pangasius fillet","basa fillet","basa fish",
        "pollock fillet","pollock patty","alaskan pollock","fish stick pollock",
        "fish sticks","fish fingers","breaded fish stick","van de kamp fish",
        "gortons fish stick","mrs paul fish stick","fisher boy fish",
        "fish fillet breaded","battered fish fillet","beer battered fish",
        "tempura fish","japanese fish tempura","fish tempura plate",
        "smoked trout","smoked mackerel","smoked whitefish","smoked herring",
        "smoked bluefish","kippered herring","finnan haddie","smoked haddock",
        "cured fish","pickled herring","herring in cream","matjes herring",
    ],

    "FoodIconPork": [
        "pork station","pork line","pork bar","pork entree",
        "pork chop dinner","pork chop plate","pork chop meal",
        "pork roast dinner","pork roast plate","roasted pork dinner",
        "carnitas station","carnitas bar","carnitas bowl","carnitas taco filling",
        "al pastor station","al pastor taco filling","al pastor pork",
        "cochinita pibil station","cochinita pibil taco","yucatan pork",
        "pernil roast","lechon asado","cuban pork","cuban roast pork",
        "char siu pork bbq","chinese bbq pork station","hong kong bbq pork",
        "roasted pork belly chinese","siu yuk crispy","crispy belly pork",
        "dongpo pork belly","hong shao rou red braised","red braised pork",
        "pork collar bbq","pork collar roasted","pork neck roasted",
        "guanciale pasta pork cheek","lardo pork fatback","pancetta pork",
        "coppa pork shoulder cured","ciccioli pork pressed","nduja spreadable",
        "luganega sausage","trentino sausage","fennel sausage fresh",
        "sweet fennel sausage","hot fennel sausage","bockwurst pork",
        "weisswurst pork veal","leberkase pork loaf","sulze headcheese",
        "schweinshaxe german pork knuckle","haxe roasted","schweinshaxe",
        "spanferkel roasted piglet","cajun boudin link","andouille pork smoked",
        "tasso pork ham smoked","debris pork po boy filling","debris roast beef",
        "banh mi pork pate","vietnamese pork patty","cha lua vietnamese",
        "korean samgyeopsal pork belly","dwaeji galbi pork ribs","jeyuk bokkeum",
        "miso glazed pork","gochujang pork","doenjang pork","ssam pork wrap",
    ],

    "FoodIconRiceBowl": [
        "rice station","rice bar","rice line","rice buffet","rice today",
        "rice options","steamed rice station","fresh rice","hot rice",
        "plain steamed rice","plain white rice","plain brown rice",
        "vegetable fried rice","mixed fried rice","combination fried rice",
        "pineapple fried rice","basil fried rice","thai basil fried rice",
        "tom yum fried rice","pad kra pao fried rice","shrimp paste fried rice",
        "crab fried rice","lobster fried rice","scallop fried rice",
        "truffle fried rice","parmesan fried rice","mushroom fried rice",
        "miso fried rice","soy fried rice","garlic butter fried rice",
        "hawaiian fried rice spam","spam musubi rice","loco moco rice",
        "chicken long rice soup","saimin noodle rice","laulau plate rice",
        "kalua pork plate rice","beef stew plate rice","shoyu chicken plate",
        "bibimbap stone pot","dolsot bibimbap hot stone","bibimbap mixed",
        "hoe dupbap raw fish rice","yukhoe dupbap beef tartare rice",
        "gyudon sukiyaki beef rice","oyakodon egg chicken rice","tendon shrimp rice",
        "unadon eel rice","kaisendon sashimi rice","magurodon tuna rice",
        "tekkadon tuna sashimi rice","negitorodon tuna rice","sake don salmon rice",
        "hokkaido bowl rice","hakodate bowl rice","sapporo rice bowl",
        "nasi uduk coconut rice","nasi kuning yellow rice","nasi goreng style rice",
        "nasi campur mixed rice","nasi padang mixed rice","nasi tumpeng cone rice",
        "arroz blanco mexican","arroz rojo red rice","arroz verde green",
        "arroz negro black rice squid","paella rice dish","paella valenciana",
        "risotto arborio","risotto milanese saffron","mushroom risotto",
        "seafood risotto","truffle risotto","lemon risotto","pea risotto",
        "miso butter risotto","barley risotto orzotto","farro risotto farrotto",
    ],

    "FoodIconWheat": [
        "oat bar","oatmeal bar","overnight oats bar","granola bar oat based",
        "oat based bar","oat cookie bar","oat square","oat biscuit",
        "muesli bar","bircher bar","swiss muesli","bircher muesli bowl",
        "ancient grain bowl","grain blend bowl","mixed grain bowl","heritage grain",
        "wheat berry salad","farro salad","einkorn salad","kamut salad",
        "bulgur pilaf","bulgur salad","bulgur tabouli","grain tabouli",
        "kasha varnishkes","kasha buckwheat","buckwheat groats","toasted buckwheat",
        "soba grain","buckwheat soba dry","buckwheat flour product","kasha side",
        "millet bowl","amaranth bowl","teff bowl","sorghum bowl","grain side dish",
        "whole grain side","multigrain side","seven grain blend","nine grain blend",
        "bran cereal","all bran","bran buds","fiber cereal all bran",
        "raisin bran crunch","total whole grain","fiber one original",
        "barbara's puffins","puffed wheat cereal","puffed kamut","puffed millet",
        "nature's path flax plus","nature's path heritage","earth friendly granola",
        "back to nature granola","purely elizabeth granola","kind granola",
        "nature valley crunchy","nature valley protein","quaker oats original",
        "quaker lower sugar oatmeal","bob's red mill oatmeal","mccann's irish oats",
        "instant oatmeal packet","flavored oatmeal instant","apple cinnamon oatmeal",
        "maple brown sugar oatmeal","peach cream oatmeal","strawberry oatmeal",
        "banana bread oatmeal instant","pumpkin spice oatmeal","pumpkin oatmeal",
    ],

    "FoodIconDonut": [
        "donut station","donut bar","donut line","fresh donut","warm donut",
        "fresh baked donut","hot donut fresh","donut of the day",
        "filled donut","cream filled donut","jelly filled donut","custard filled",
        "lemon curd donut","nutella filled donut","maple cream donut",
        "peanut butter donut","pb&j donut","s'mores donut","campfire donut",
        "birthday cake donut","funfetti donut","rainbow sprinkle donut",
        "cotton candy donut","lucky charms donut","cereal donut","fruity pebbles donut",
        "bacon donut","maple bacon donut","candied bacon donut","sweet and savory donut",
        "lavender donut","rose donut","earl grey donut","matcha donut",
        "ube donut","black sesame donut","hojicha donut","yuzu donut","miso donut",
        "pumpkin donut fall","apple cider donut fall","spiced donut","chai donut",
        "cardamom donut","gingerbread donut","eggnog donut","peppermint donut",
        "red velvet donut","carrot cake donut","strawberry shortcake donut",
        "banana foster donut","key lime donut","passion fruit donut",
        "voodoo donut","blue star donut","top pot donut","sidecar donut",
        "psycho donuts","do-rite donuts","glaze donut shop","underwest donuts",
        "dough brooklyn","donut pub nyc","peter pan donuts","the donut pub",
        "donut plant nyc","doughnut project","donut friend la","fonuts la",
        "california donut la","dk donuts","district donuts","revolution donuts",
    ],

    "FoodIconFries": [
        "fries station","fry station","french fry station","fry bar","fry line",
        "fresh cut fries","fresh fries","hot fries","seasoned fries station",
        "garlic parmesan fries station","loaded fries station","special fries",
        "thick cut steak fry","double dipped fry","extra crispy fry",
        "matchstick fry","julienne fry","gaufrette fry","lattice fry",
        "basket of fries","cone of fries","paper cup fries","fry cup",
        "small fry order","medium fry order","large fry order","supersized fry",
        "five guys style fry","in n out fry","shake shack fry","whataburger fry",
        "wendy's natural fry","mcdonalds world famous fry","bk fry",
        "jack in the box fry","del taco fry","carls jr fry","hardee's fry",
        "sonic seasoned tot","sonic chili cheese tot","sonic tater tot",
        "ore ida tater tot","frozen tater tot","baked tater tot","air fry tot",
        "jo jo potato","jo jo wedge","seasoned wedge potato","ranch wedge",
        "country potato","country fried potato","home fry potato","skillet fry",
        "potato wedge seasoned","oven potato wedge","roasted wedge",
        "disco fries gravy cheese","jersey disco fry","poutine classic",
        "montreal poutine","smoked meat poutine","pulled pork poutine",
        "lobster poutine","foie gras poutine","vegan poutine","kimchi poutine",
    ],

    "FoodIconGlassWater": [
        "infused water pitcher","fruit infused water","cucumber mint water",
        "lemon ginger water","strawberry basil water","watermelon mint water",
        "spa water","detox water","cleanse water","wellness water",
        "alkaline ionized water","kangen water","ionized alkaline",
        "glaceau smartwater electrolyte","smartwater vapor distilled",
        "essentia alkaline water","core hydration water","flow alkaline water",
        "waiakea volcanic water","volvic water","vittel water","contrex water",
        "san pellegrino sparkling","acqua panna still","pellegrino can",
        "gerolsteiner sparkling","badoit sparkling","harrogate sparkling",
        "saratoga sparkling water","seltzer plain","club soda plain","soda water",
        "plain sparkling","unflavored sparkling water","sparkling plain",
        "bubbly plain sparkling","waterloo plain","polar seltzer plain",
        "white claw pure seltzer","truly wild berry seltzer","vizzy seltzer plain",
        "nutrl seltzer","liquid death plain","liquid death still",
        "water intake","hydration log","daily water","drinking water log",
        "water bottle","reusable water bottle content","water cup cafeteria",
        "glass of ice water","pitcher of water","water carafe","water decanter",
    ],

    "FoodIconEgg": [
        "egg station","egg bar","egg line","build your own egg","egg buffet",
        "breakfast egg station","omelette station","omelette bar","omelette line",
        "made to order eggs","eggs to order","egg any style","egg your way",
        "scrambled egg station","hard cooked egg station","poached egg station",
        "egg white scramble","egg substitute scramble","egg beaters",
        "just egg plant based","follow your heart vegan egg",
        "tofu scramble egg style","chickpea scramble egg style",
        "quail egg","quail egg soft boiled","quail egg deviled","quail egg nest",
        "duck egg","duck egg fried","duck egg scrambled","preserved duck egg",
        "goose egg","ostrich egg","emu egg","free range egg dish",
        "pastured egg dish","heritage egg","colorful egg","araucana egg",
        "blue egg","green egg","brown egg protein","white egg protein",
        "egg white protein","liquid egg white","carton egg white","pure egg white",
        "whole egg protein","whole egg dish","egg protein snack","egg bite",
        "sous vide egg bite","starbucks egg bite","copycat egg bite",
        "mini egg frittata","crustless quiche","egg muffin cup","egg cup baked",
        "egg casserole slice","overnight egg casserole","egg bake slice",
        "shakshuka baked egg","eggs en cocotte","baked egg ramekin",
        "turkish egg cilbir","iranian egg mirza","greek egg strapatsada",
        "spanish egg revueltos","french omelette classic","denver omelette",
        "western omelette","spanish omelette tortilla","frittata wedge",
    ],

    "FoodIconIceCream": [
        "ice cream cone station","ice cream cone bar","ice cream scoop station",
        "soft serve cone station","cone station ice cream","cone line",
        "single scoop cone station","double cone station","ice cream dip station",
        "hard ice cream station","scooped ice cream cone","hand dipped cone",
        "rolled waffle cone","fresh waffle cone","house made waffle cone",
        "sugar cone station","cake cone station","wafer cone plain",
        "rainbow sherbet cone","orange sherbet cone","lime sherbet cone",
        "rainbow swirl cone outdoor","carnival ice cream cone","fair cone",
        "amusement park ice cream","theme park cone","boardwalk cone",
        "custard cone concrete","concrete frozen custard","thick frozen custard cone",
        "overrun cone","cheap ice cream cone","self serve cone machine",
        "twist cone machine","swirl machine cone","vanilla chocolate twist",
        "strawberry vanilla twist","strawberry chocolate twist","rainbow twist",
        "chocolate dip cone hard shell","cherry dip cone","blueberry dip cone",
        "butterscotch dip cone","rainbow dip cone","cotton candy dip",
        "dreyers ice cream cone","breyers cone","turkey hill cone","blue bell cone",
        "tillamook cone","alden's organic cone","three twins cone","straus cone",
    ],

    "FoodIconMicrowave": [
        "frozen entree","frozen dinner entrée","frozen breakfast","frozen lunch",
        "frozen burrito microwave","frozen mac and cheese","frozen pasta","frozen rice",
        "frozen veggie burger","frozen meat","frozen pot pie","frozen casserole",
        "microwave bowl","microwave cup","microwave mac","microwave ramen",
        "microwave rice bowl","microwave burrito","microwave breakfast sandwich",
        "microwave oatmeal","microwave popcorn bag","microwave potato",
        "microwave baked potato","microwave sweet potato","microwave corn",
        "steam bag vegetables","steam in bag broccoli","steam bag green beans",
        "steam bag peas","steam bag cauliflower","steam bag mixed veg",
        "ready meal uk","ready to eat meal","heat and serve","heat and eat",
        "shelf stable meal","retort pouch meal","mre meal ready to eat",
        "emergency food","survival food kit","camping meal packet",
        "backpacking meal","mountain house meal","good to go meal","trailtopia",
        "minute rice microwavable","uncle ben's ready rice","birds eye ready rice",
        "success boil in bag","knorr pasta sides microwave","rice a roni microwavable",
        "pasta roni microwavable","velveeta shells microwave","kraft cup mac",
        "campbell's soup microwave","progresso soup microwavable","hormel soup cup",
        "dinty moore cup","chef boyardee cup","campbell's chunky can",
    ],

    "FoodIconBread": [
        "bread station","bread bar","bread line","fresh bread station",
        "bread basket","bread service","dinner bread","table bread","roll basket",
        "artisan bread station","bread bakery station","fresh baked bread station",
        "house bread","house made bread","housemade bread","made in house bread",
        "bread of the day","daily bread","bread assortment","bread variety",
        "breadstick","garlic breadstick","cheese breadstick","olive oil breadstick",
        "focaccia slice","focaccia square","thick focaccia","rosemary focaccia",
        "olive focaccia","tomato focaccia","onion focaccia","herb focaccia",
        "naan fresh baked","garlic naan","cheese naan","butter naan","peshwari naan",
        "keema naan","paneer naan","stuffed naan","tawa naan","tandoor naan",
        "paratha plain","aloo paratha","gobi paratha","palak paratha","methi paratha",
        "chapati whole wheat","roti whole wheat","phulka thin roti","tandoori roti",
        "puri fried bread","bhatura fried bread","luchi fried","poori fried",
        "injera sourdough teff","injera ethiopian","injera fermented",
        "teff flatbread","berbere bread","habesha bread","ambasha bread",
        "lavash thin armenian","lavash crispy","lavash soft","mountain bread",
        "taboon bread","markook bread","saj bread","taboon oven bread",
        "pide turkish bread","lahmacun bread","simit sesame ring",
        "pretzel soft large","pretzel soft stick","pretzel knot soft",
        "auntie anne's pretzel","wetzel's pretzels","philly pretzel factory",
        "hard pretzel nuggets","pretzel thin crisps","pretzel rod",
    ],

    "FoodIconCupSoda": [
        "boba tea","bubble tea","milk tea","tapioca milk tea","pearl milk tea",
        "taro milk tea","matcha milk tea","thai milk tea","hong kong milk tea",
        "brown sugar milk tea","tiger milk tea","dirty milk tea","cheese tea",
        "fresh fruit tea","passion fruit tea","mango tea","peach tea boba",
        "strawberry matcha latte","brown sugar latte","boba latte","boba coffee",
        "tapioca pearls drink","popping boba drink","egg pudding drink","taro drink",
        "gongcha boba","tiger sugar boba","koi boba","chatime boba","coco boba",
        "85 degrees boba","sharetea boba","happy lemon boba","presotea boba",
        "punch bowl social","mixology drink","mocktail","virgin cocktail",
        "shirley temple drink","roy rogers drink","arnold palmer","half and half",
        "lemonade stand","fresh squeezed lemonade","hand squeezed lemonade",
        "minute maid lemonade","simply lemonade","newman's lemonade",
        "tropicana lemonade","country time lemonade","mike's lemonade alcohol",
        "cherry limeade sonic","slush sonic","ocean water sonic","sunset drink",
        "jamba juice smoothie","jamba juice drink","naked juice bottle",
        "odwalla juice","bolthouse farms smoothie","green smoothie bottle",
        "smoothie king smoothie","tropical smoothie cafe","planet smoothie",
        "frullati smoothie","robeks smoothie","surf city squeeze","orange julius",
        "freshii smoothie","pressed juicery","juice press","blueprint juice",
        "suja juice","cold pressed juice","green juice pressed","cleanse juice",
        "kombucha gt's","health ade kombucha","brew dr kombucha","humm kombucha",
        "kevita kombucha","synergy kombucha","live soda kombucha","wonder drink",
    ],

    "FoodIconHam": [
        "charcuterie board","charcuterie plate","meat board","cured meat board",
        "charcuterie platter","deli platter","meat and cheese platter",
        "salumi board","italian cured meats","antipasto platter meats",
        "bresaola cured beef","speck cured ham","lonza pork loin cured",
        "lardo fatback cured","pancetta unsmoked","pancetta smoked","guanciale cured",
        "jambon de paris","jambon beurre","french ham sandwich","parisian ham",
        "jamón jamón spanish","pata negra ham","cured spanish ham",
        "black forest ham slice","honey ham slice","virginia ham slice",
        "pit ham smoked","country ham salt cured","red eye gravy ham",
        "ham steak grilled","ham steak baked","bone in ham steak",
        "deli turkey thin sliced","smoked turkey breast sliced","turkey lunch meat",
        "roasted turkey deli","mesquite turkey deli","honey turkey deli",
        "turkey pepperoni","turkey salami","turkey bologna","turkey ham",
        "chicken breast deli sliced","grilled chicken cold deli","rotisserie chicken cold",
        "chicken mortadella","chicken bologna deli","chicken salami deli",
        "roast beef deli thin","roast beef cold cut","london broil deli",
        "corned beef deli slice","pastrami deli slice","pastrami thin sliced",
        "tongue deli","beef tongue sliced","smoked tongue cold cut",
        "liverwurst braunschweiger","braunschweiger spread","liverwurst spread",
        "pate country terrine","duck pate","chicken liver pate","pork pate",
    ],

    "FoodIconPopcorn": [
        "popcorn bar","popcorn station","popcorn line","fresh popped popcorn",
        "hot popcorn fresh","flavored popcorn station","gourmet popcorn station",
        "chicago mix station","kettle corn station","caramel corn station",
        "movie popcorn large tub","cinema popcorn","theater popcorn",
        "concession popcorn","stadium popcorn","fair popcorn","carnival popcorn",
        "cheddar jalapeno popcorn","white cheddar jalapeno popcorn",
        "carolina reaper popcorn","scorpion pepper popcorn","extreme heat popcorn",
        "sweet and spicy popcorn","honey sriracha popcorn","chili honey popcorn",
        "cinnamon sugar popcorn","caramel sea salt popcorn","dark chocolate popcorn",
        "chocolate drizzle popcorn","yogurt covered popcorn","peanut butter popcorn",
        "s'mores popcorn","birthday cake popcorn bag","funfetti popcorn bag",
        "cotton candy popcorn","raspberry popcorn","coconut popcorn","lime popcorn",
        "dill pickle popcorn bag","everything bagel popcorn bag","furikake popcorn",
        "seaweed popcorn","japanese popcorn flavor","korean popcorn flavor",
        "popcorn indiana","pipsnacks pipcorn","lesser evil paleo","angie's boomchick",
        "skinny pop bag","skinny pop original","skinny pop white cheddar",
        "boomchickapop light","boom chicka pop kettle","quinn popcorn",
        "popcornopolis cone","chicago mix tin","holiday popcorn tin",
        "flavored popcorn gift","popcorn sampler","popcorn variety pack",
    ],

    "FoodIconProtein": [
        # Keep protein bar examples very specific to bars/shakes/supplements
        # Remove confusion with salad bar, dessert bar etc.
        "protein supplement","protein supplement bar","supplement bar","gym bar",
        "fitness bar","workout bar","muscle bar","performance bar",
        "post workout bar","pre workout snack bar","recovery bar","sport bar food",
        "bodybuilding bar","weight training snack","lifting snack",
        "meal replacement bar","diet bar","low calorie bar","high protein snack",
        "built bar chocolate","built bar coconut","built bar strawberry",
        "rxbar egg white based","rxbar chocolate sea salt","rxbar blueberry",
        "perfect bar dark chocolate","perfect bar almond butter","perfect bar peanut",
        "gomacro macrobar","sunwarrior bar","vega sport bar","orgain bar",
        "pure protein bar chocolate","pure protein bar white chocolate",
        "fitjoy bar birthday cake","fitjoy bar chocolate chip","fitjoy bar vanilla",
        "no cow bar lemon","no cow bar chocolate fudge","no cow bar peanut butter",
        "aloha bar chocolate","aloha bar vanilla","aloha bar coconut",
        "epic bar beef","epic bar chicken sesame","epic bar venison",
        "chomps beef stick","chomps turkey stick","chomps venison stick",
        "slim jim beef stick","jack links beef stick","oh snap pickle",
        "country archer beef stick","epic venison bar","krave jerky bar",
        "protein powder scoop","whey protein scoop","casein powder scoop",
        "pea protein scoop","hemp protein scoop","brown rice protein",
        "protein shake premade","protein shake homemade","protein smoothie made",
        "creatine supplement","creatine monohydrate","creatine powder",
        "bcaa drink","eaa drink","amino drink","glutamine supplement",
        "collagen peptide powder","collagen supplement","collagen protein",
    ],

    "FoodIconPizza": [
        # Station/line name fixes
        "pizza bar station menu","pizza buffet line","fresh baked pizza station",
        "hot pizza line","pizza of the day station","hand tossed pizza station",
    ],

    "FoodIconCookie": [
        # More cookie station entries
        "cookie station","cookie bar","cookie line","fresh baked cookie station",
        "cookie buffet","warm cookie","hot cookie fresh baked","cookie of the day",
        "cookie assortment","cookie variety","bakery cookie station",
    ],

    "FoodIconChefHat": [
        "chef bar","station name","cafeteria station","dining hall station",
        "dining hall special","residence hall dining","university dining",
        "college dining special","campus dining special","food court special",
        "cafe special today","bistro special","diner special today",
        "local catch","farm fresh today","market fresh today",
        "created by chef","chef created item","executive chef item",
        "tasting menu item today","prix fixe today","featured creation",
    ],

    "FoodIconGrape": [
        "grape station","grape bunch","grape cluster","grape portion",
        "grape snack individual","seedless grape portion","table grape serving",
        "red globe grape","green globe grape","cotton candy grape individual",
        "concord grape fresh","muscadine grape","scuppernong grape",
        "champagne grape small","pixie grape","christmas grape",
        "moon drop grape","gum drop grape","sweet sapphire grape",
        "autumn king grape","adora seedless grape","sweet globe grape",
        "magenta pearl grape","carnival grape","starlight grape",
        "grape juice 100%","welch's grape juice","concord grape juice",
        "sparkling grape juice","martinelli's grape","welch's sparkling grape",
        "grape flavored drink","grape popsicle","grape flavored snack",
        "raisin snack box","mini raisin box","sun maid raisins","dole raisins",
        "golden raisin snack","mixed dried fruit raisin","yogurt raisin",
        "chocolate raisin","raisinets","goobers raisin chocolate",
    ],

    "FoodIconCarrot": [
        "carrot station","carrot snack cup","carrot snack bag","carrot individual",
        "baby carrot bag","baby carrot cup","carrot dip snack","carrot hummus snack",
        "carrot and hummus pack","ranch and carrot pack","carrot ranch dip",
        "carrot celery snack","veggie snack pack carrot","snack pack veggies",
        "carrot cake treat","carrot muffin","carrot bread","carrot loaf",
        "carrot soup creamy","carrot ginger creamy","carrot apple soup",
        "carrot orange soup","thai carrot soup","moroccan carrot soup",
        "roasted carrot soup","carrot puree soup","carrot lentil soup",
        "glazed carrot side","honey glazed carrot","maple glazed carrot",
        "brown sugar carrot","balsamic carrot","harissa carrot","cumin carrot",
        "carrot and parsnip","root vegetable medley carrot","roasted root carrot",
        "steamed carrot side","blanched carrot","carrot au gratin",
        "carrot vichy","vichy carrots","carottes vichy","french carrot",
        "carrot pickle","pickled carrot","carrot kimchi","carrot achar",
        "carrot crudité","crudite carrot","veggie platter carrot",
    ],

    "FoodIconCitrus": [
        "orange snack","orange fruit","fresh orange","peeled orange","orange cup",
        "orange segments cup","mandarin cup","clementine peeled","easy peel orange",
        "cutie orange","halo orange","cuties clementines","halos mandarin",
        "mandarin orange cup","dole mandarin cup","del monte mandarin cup",
        "grapefruit half","grapefruit wedge","broiled grapefruit","grapefruit cup",
        "citrus fruit cup","citrus mix","citrus salad","citrus fruit salad",
        "citrus station","fresh citrus","seasonal citrus","winter citrus",
        "blood orange segment","blood orange salad","blood orange dessert",
        "cara cara segment","cara cara salad","cara cara dessert",
        "navel orange slice","orange slice garnish","orange wheel",
        "lemon slice","lemon wedge","lemon garnish","fresh lemon",
        "lime wedge","lime slice","lime garnish","fresh lime","key lime",
        "yuzu citrus","yuzu juice","yuzu zest","yuzu dressing",
        "orange zest","lemon zest","lime zest","citrus zest",
        "orange cream","orange curd","lemon curd","lime curd",
        "orange marmalade","lemon marmalade","grapefruit marmalade",
    ],

    "FoodIconBanana": [
        "banana station","banana fresh","banana individual","banana single",
        "banana snack individual","banana to go","whole banana snack",
        "green tipped banana","just ripe banana","very ripe banana",
        "organic banana individual","fair trade banana","rainforest alliance banana",
        "banana boat snack","banana oat cookies","banana oatmeal","banana oat bar",
        "banana nice cream","frozen banana blended","banana soft serve",
        "banana ice cream","one ingredient banana ice cream","nicecream banana",
        "banana nut bread","banana walnut bread","banana chocolate chip bread",
        "banana muffin","banana streusel muffin","banana blueberry muffin",
        "banana pancake","banana oat pancake","banana protein pancake",
        "banana crepe","banana french toast","banana stuffed french toast",
        "bananas foster sauce","foster sauce banana","rum banana sauce",
        "banana split classic","banana split sundae","banana split boat",
        "banana pudding cup","magnolia banana pudding","old fashioned banana pudding",
        "banana cream pie slice","banana cream dessert","banana custard",
        "dried banana chip","banana chip snack bag","plantain chip",
        "savory plantain","sweet plantain","fried sweet plantain","tostones fried",
        "maduros sweet fried","platano maduro","patacones twice fried",
    ],

    "FoodIconMilk": [
        # Fix the yogurt issue — also add more dairy
        "cottage cheese cup","cottage cheese snack","small curd cottage",
        "lowfat cottage cheese","daisy cottage cheese cup","good culture cottage",
        "hood cottage cheese","friendship cottage","horizon organic cottage",
        "string cheese","mozzarella stick cheese snack","babybel cheese",
        "laughing cow cheese","mini babybel","cheese round snack",
        "colby jack stick","cheddar stick","pepper jack stick","cheese stick snack",
        "cheese cube snack","cheese snack individual","snack cheese portion",
        "greek yogurt cup individual","single serve yogurt","yogurt snack size",
        "yogurt tube kids","go-gurt tube","danimals squeezable",
        "milk carton school","school milk","white milk carton",
        "chocolate milk carton","strawberry milk carton","lowfat school milk",
        "fairlife milk protein","fair life ultra filtered","lactaid milk",
        "organic valley milk","horizon organic milk","straus organic milk",
        "local dairy milk","farm fresh milk","grass fed milk","jersey milk",
        "a2 whole milk","a2 milk protein","goat milk fresh",
    ],
}

# ─── Load and merge ──────────────────────────────────────────────────────────
def load_csv(path: str) -> list[tuple[str, str]]:
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            rows.append((row["text"], row["label"]))
    return rows

base_dir = os.path.dirname(__file__)
train_path = os.path.join(base_dir, "training_data.csv")
val_path   = os.path.join(base_dir, "validation_data.csv")

existing = load_csv(train_path) + load_csv(val_path)
new_rows: list[tuple[str, str]] = []
for label, examples in additions.items():
    for text in examples:
        new_rows.append((text.strip(), label))

all_rows = existing + new_rows
random.shuffle(all_rows)

split = int(len(all_rows) * 0.85)
train_rows = all_rows[:split]
val_rows   = all_rows[split:]

def write_csv(path: str, rows: list[tuple[str, str]]) -> None:
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["text", "label"])
        writer.writerows(rows)

write_csv(train_path, train_rows)
write_csv(val_path,   val_rows)

from collections import Counter
counts = Counter(label for _, label in all_rows)
print(f"Total examples : {len(all_rows)}")
print(f"Training rows  : {len(train_rows)}")
print(f"Validation rows: {len(val_rows)}")
print(f"Classes        : {len(counts)}")
print(f"\nSmallest 10:")
for label, n in sorted(counts.items(), key=lambda x: x[1])[:10]:
    print(f"  {label:38s} {n:4d}")
print(f"\nLargest 10:")
for label, n in sorted(counts.items(), key=lambda x: x[1], reverse=True)[:10]:
    print(f"  {label:38s} {n:4d}")
