#!/usr/bin/env python3
"""expand_v5.py — targeted fixes for round 5 misclassifications + broad coverage improvements.

Issues fixed:
1. "Farmer's Breakfast Casserole" → FoodIconProtein   Fix: mass casserole→Egg/CookingPot examples
2. "Fruit Smoothies" → FoodIconApple                  Fix: fruit smoothie→CupSoda examples
3. Generic "smoothie" fragmented across classes        Fix: anchor smoothie station names to CupSoda
4. Missing breakfast foods (waffle, pancake, etc.)     Fix: add breakfast station coverage
5. Missing casserole/baked dish coverage               Fix: casserole→CookingPot / breakfast casserole→Egg
6. Weak pasta/grain station names                      Fix: add station-style examples
7. Missing juice/beverage station names                Fix: add juice bar / smoothie bar coverage
"""

import csv, pathlib, random

ROOT = pathlib.Path(__file__).parent
TRAIN_IN  = ROOT / "training_data.csv"
VAL_IN    = ROOT / "validation_data.csv"

random.seed(202)

def load(path):
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            rows.append({"text": r["text"], "label": r["label"]})
    return rows

def save(path, rows):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["text","label"])
        w.writeheader()
        w.writerows(rows)

train_rows = load(TRAIN_IN)
val_rows   = load(VAL_IN)

ADDITIONS = []

def add(label, *texts):
    for t in texts:
        ADDITIONS.append({"text": t.strip(), "label": label})

# ─── 1. CASSEROLE — FoodIconEgg for breakfast variants, FoodIconCookingPot for generic ───

# Breakfast casseroles are egg-based baked dishes → EGG icon
add("FoodIconEgg",
    # Direct PCC/cafeteria station names
    "farmers breakfast casserole",
    "farmer's breakfast casserole",
    "farmers breakfast casserole station",
    "breakfast casserole",
    "breakfast casserole station",
    "breakfast casserole bar",
    "breakfast casserole line",
    "egg casserole",
    "egg casserole station",
    "egg bake",
    "egg bake station",
    "baked egg dish",
    "baked eggs",
    "egg bake casserole",
    "cheesy egg casserole",
    "sausage egg casserole",
    "ham egg casserole",
    "veggie egg casserole",
    "vegetable egg casserole",
    "spinach egg casserole",
    "mushroom egg casserole",
    "southwestern egg casserole",
    "denver egg casserole",
    "brunch casserole",
    "brunch egg bake",
    "morning casserole",
    "morning egg bake",
    "farmers casserole",
    "farmer casserole",
    "hash brown casserole",
    "hashbrown casserole",
    "potato egg casserole",
    "cheesy hashbrown casserole",
    "tater tot casserole breakfast",
    "egg and cheese casserole",
    "eggs and cheese casserole",
    "frittata station",
    "frittata",
    "baked frittata",
    "oven frittata",
    "strata",
    "egg strata",
    "bread strata",
    "savory strata",
    "overnight egg bake",
    "overnight breakfast casserole",
    "make ahead breakfast casserole",
    # Egg items missing from training
    "scrambled eggs",
    "scrambled egg",
    "soft scrambled eggs",
    "hard scrambled eggs",
    "fluffy scrambled eggs",
    "cheesy scrambled eggs",
    "scrambled egg station",
    "scrambled eggs station",
    "omelette",
    "omelettes",
    "omelet",
    "omelets",
    "made to order omelette",
    "custom omelette",
    "omelette bar",
    "omelette station",
    "omelette bar station",
    "build your own omelette",
    "egg omelette",
    "veggie omelette",
    "cheese omelette",
    "ham and cheese omelette",
    "western omelette",
    "denver omelette",
    "spinach omelette",
    "mushroom omelette",
    "greek omelette",
    "quiche",
    "quiche lorraine",
    "spinach quiche",
    "veggie quiche",
    "ham and cheese quiche",
    "egg quiche",
    "mini quiche",
    "crustless quiche",
    "breakfast quiche",
    "hash brown",
    "hash browns",
    "hashbrown",
    "hashbrowns",
    "shredded hash browns",
    "crispy hash browns",
    "potato hash",
    "breakfast potatoes",
    "home fries",
    "country potatoes",
    "skillet potatoes",
    "potato scramble",
    "hard boiled egg",
    "hard boiled eggs",
    "hard cooked egg",
    "soft boiled egg",
    "deviled egg",
    "deviled eggs",
    "poached egg",
    "poached eggs",
    "eggs benedict",
    "eggs florentine",
    "hollandaise",
    "breakfast egg",
    "morning egg",
    "egg white omelette",
    "egg white scramble",
)

# Generic non-breakfast casseroles → COOKINGPOT icon
add("FoodIconCookingPot",
    "casserole",
    "casseroles",
    "baked casserole",
    "casserole dish",
    "chicken casserole",
    "tuna casserole",
    "tuna noodle casserole",
    "beef casserole",
    "vegetable casserole",
    "veggie casserole",
    "rice casserole",
    "pasta casserole",
    "noodle casserole",
    "green bean casserole",
    "sweet potato casserole",
    "broccoli casserole",
    "corn casserole",
    "enchilada casserole",
    "tamale casserole",
    "shepherd's pie",
    "shepherds pie",
    "cottage pie",
    "pot pie",
    "chicken pot pie",
    "beef pot pie",
    "turkey pot pie",
    "cobbler savory",
    "baked dish",
    "oven baked dish",
    "hotdish",
    "hot dish",
    "minnesota hotdish",
    "church potluck",
)

# ─── 2. SMOOTHIE / JUICE / BEVERAGE STATION → FoodIconCupSoda ─────────────────

add("FoodIconCupSoda",
    # Smoothie stations — the key missing cases
    "fruit smoothie",
    "fruit smoothies",
    "fruit smoothie station",
    "fruit smoothie bar",
    "fruit smoothie line",
    "fruit smoothies station",
    "fresh fruit smoothie",
    "fresh fruit smoothies",
    "made to order smoothie",
    "made to order smoothies",
    "build your own smoothie",
    "smoothie station",
    "smoothie bar",
    "smoothie bar station",
    "smoothie line",
    "smoothie bar line",
    "fresh smoothie",
    "fresh smoothies",
    "daily smoothie",
    "smoothie of the day",
    "signature smoothie",
    "smoothie blend",
    "blended smoothie",
    "blended drink",
    "blended drinks",
    "blended beverage",
    "blended beverages",
    "blended fruit drink",
    "smoothie",
    "smoothies",
    "tropical smoothie",
    "tropical smoothies",
    "mango smoothie",
    "strawberry smoothie",
    "peach smoothie",
    "mixed berry smoothie",
    "berry smoothie",
    "citrus smoothie",
    "pineapple smoothie",
    "watermelon smoothie",
    "melon smoothie",
    "kiwi smoothie",
    "green smoothie",
    "veggie smoothie",
    "spinach smoothie",
    "kale smoothie",
    "smoothie with spinach",
    # Juice bar / beverage stations
    "juice bar",
    "juice bar station",
    "juice station",
    "juice line",
    "fresh juice",
    "fresh squeezed juice",
    "fresh squeezed",
    "cold pressed juice",
    "cold press juice",
    "pressed juice",
    "juice of the day",
    "fruit juice station",
    "fruit juice bar",
    "fruit juices",
    "juice blend",
    "juice blends",
    "fresh fruit juice",
    "fruit punch station",
    "lemonade station",
    "lemonade bar",
    "lemonade stand",
    "fresh lemonade",
    "flavored lemonade",
    "agua fresca",
    "agua fresca station",
    "agua fresca bar",
    "horchata",
    "iced tea station",
    "tea station",
    "beverage station",
    "beverage bar",
    "drink station",
    "drink bar",
    "fountain drinks",
    "fountain beverage",
    "soda fountain",
    "soda station",
    "soda bar",
    "pop station",
    "soft drink station",
    "sparkling water station",
    "flavored water station",
    "infused water station",
    "water station",
    "coffee and juice",
    "juice and coffee",
)

# ─── 3. PANCAKE / WAFFLE / FRENCH TOAST → FoodIconCroissant ──────────────────

add("FoodIconCroissant",
    "pancake",
    "pancakes",
    "pancake station",
    "pancake bar",
    "pancake line",
    "made to order pancakes",
    "buttermilk pancake",
    "buttermilk pancakes",
    "blueberry pancake",
    "blueberry pancakes",
    "chocolate chip pancake",
    "chocolate chip pancakes",
    "banana pancake",
    "banana pancakes",
    "silver dollar pancakes",
    "mini pancakes",
    "fluffy pancakes",
    "thick pancakes",
    "griddle pancakes",
    "waffle",
    "waffles",
    "waffle station",
    "waffle bar",
    "waffle line",
    "made to order waffle",
    "belgian waffle",
    "belgian waffles",
    "classic waffle",
    "crispy waffle",
    "waffle iron station",
    "build your own waffle",
    "waffle bar toppings",
    "blueberry waffle",
    "chocolate waffle",
    "strawberry waffle",
    "waffle and toppings",
    "waffle with syrup",
    "french toast",
    "french toast station",
    "french toast bar",
    "french toast line",
    "baked french toast",
    "stuffed french toast",
    "cinnamon french toast",
    "brioche french toast",
    "sourdough french toast",
    "thick cut french toast",
    "french toast casserole",
    "overnight french toast",
    "texas toast",
    "toast station",
    "toast bar",
    "toast and jam",
    "avocado toast station",
    "avocado toast",
    "biscuit and gravy",
    "biscuits and gravy",
    "biscuit station",
    "biscuits",
    "southern biscuits",
    "gravy station",
    "sausage gravy",
    "country gravy",
    "white gravy",
    "crepe",
    "crepes",
    "crepe station",
    "crepe bar",
    "made to order crepe",
    "sweet crepe",
    "savory crepe",
    "croissant",
    "croissants",
    "croissant station",
    "butter croissant",
    "almond croissant",
    "chocolate croissant",
    "scone",
    "scones",
    "cinnamon roll station",
    "cinnamon roll",
    "sticky bun station",
    "danish station",
    "danish pastry",
    "morning pastry",
    "morning pastries",
    "breakfast pastry",
    "breakfast pastries",
)

# ─── 4. MORE BREAKFAST STATION COVERAGE ──────────────────────────────────────

add("FoodIconEgg",
    # Broad breakfast station naming patterns
    "breakfast station",
    "breakfast bar",
    "breakfast line",
    "breakfast buffet",
    "hot breakfast station",
    "hot breakfast bar",
    "hot breakfast line",
    "full breakfast station",
    "american breakfast",
    "continental breakfast",
    "breakfast items",
    "breakfast selections",
    "breakfast menu",
    "morning items",
    "morning station",
    "morning bar",
    "morning line",
    "morning selections",
    # Egg-centric terms
    "eggs any style",
    "eggs to order",
    "eggs made to order",
    "cooked to order eggs",
    "fresh eggs",
    "farm fresh eggs",
    "local eggs",
    "cage free eggs",
    # Egg preparations
    "benedict",
    "eggs royale",
    "egg white",
    "egg whites",
    "liquid eggs",
    "whole egg scramble",
    "veggie egg scramble",
    "southwest scramble",
    "breakfast scramble",
    "tofu scramble",
    "egg scramble",
)

# ─── 5. PROTEIN — tighten to actual protein supplements / branded bars ────────
# Remove broad "breakfast bar" overlap that confuses cafeteria station names
# (these are already covered in expand_v4, just reinforcing)
add("FoodIconProtein",
    # Only literal supplement / branded bar names
    "whey protein shake",
    "whey protein powder",
    "casein protein",
    "mass gainer shake",
    "protein supplement",
    "bcaa drink",
    "eaa drink",
    "creatine supplement",
    "pre workout",
    "post workout shake",
    "quest protein bar",
    "rxbar",
    "built bar",
    "one bar",
    "think thin bar",
    "combat crunch bar",
    "premier protein bar",
    "pure protein bar",
    "muscle milk bar",
    "myoplex bar",
    "met rx bar",
    "zone bar",
    "balance bar",
    "powerbar",
    "luna bar",
    "clif bar",
    "larabar",
    "kind protein bar",
    "kind bar protein",
)

# ─── 6. SALAD BAR / VEGGIE STATION ───────────────────────────────────────────

add("FoodIconSalad",
    "fresh salad station",
    "tossed salad station",
    "mixed green salad",
    "spring mix salad",
    "house salad station",
    "side salad station",
    "salad and soup station",
    "greek salad station",
    "caesar salad station",
    "chopped salad station",
    "garden salad station",
    "leafy greens station",
    "fresh greens station",
    "greens station",
    "build a salad",
    "make your own salad",
    "salad fixings",
    "salad toppings station",
    "salad dressing station",
    "grain and greens station",
    "grain and greens bar",
    "fresh veggie station",
    "veggie station",
    "vegetable station",
    "crudite station",
    "crudités station",
    "antipasto station",
    "poke bowl station",
    "grain bowl station",
    "buddha bowl station",
    "power bowl station",
    "harvest bowl station",
)

# ─── 7. SOUP STATION ─────────────────────────────────────────────────────────

add("FoodIconSoup",
    "soup of the day",
    "daily soup",
    "soup and bread",
    "soup and sandwich station",
    "cream of",
    "cream soup",
    "tomato soup",
    "tomato basil soup",
    "chicken noodle soup",
    "chicken soup",
    "vegetable soup",
    "lentil soup station",
    "split pea soup",
    "beef barley soup",
    "black bean soup",
    "white bean soup",
    "mushroom soup",
    "potato soup",
    "broccoli cheddar soup",
    "french onion soup",
    "clam chowder",
    "new england chowder",
    "manhattan chowder",
    "corn chowder",
    "lobster bisque",
    "butternut squash soup",
    "pumpkin soup",
    "tortilla soup",
    "pozole",
    "menudo",
    "hot and sour soup",
    "egg drop soup",
    "soup station",
    "soup line",
    "soup pot station",
)

# ─── 8. PASTA / GRAIN STATION ────────────────────────────────────────────────

add("FoodIconPasta",
    "pasta station",
    "pasta bar",
    "pasta line",
    "pasta bar station",
    "build your own pasta",
    "make your own pasta",
    "fresh pasta station",
    "pasta of the day",
    "daily pasta",
    "mac and cheese station",
    "macaroni station",
    "baked mac and cheese",
    "mac and cheese bar",
    "pasta primavera station",
    "spaghetti station",
    "spaghetti and meatballs station",
    "baked ziti station",
    "baked pasta station",
    "noodle station",
    "noodle bar",
    "penne station",
    "fettuccine station",
    "linguine station",
    "rigatoni station",
    "farfalle station",
    "rotini station",
    "orzo station",
    "pasta salad station",
    "cold pasta station",
    "italian station",
    "italian food station",
    "italian bar",
)

# ─── 9. RICE / GRAIN BOWL STATION ────────────────────────────────────────────

add("FoodIconRiceBowl",
    "rice station",
    "rice bar",
    "rice line",
    "fried rice station",
    "steamed rice station",
    "brown rice station",
    "white rice station",
    "jasmine rice station",
    "basmati rice station",
    "rice and beans station",
    "rice bowl station",
    "grain station",
    "grain bar",
    "grain line",
    "grain bowl bar",
    "whole grain station",
    "quinoa station",
    "quinoa bowl station",
    "quinoa bar",
    "farro station",
    "wild rice station",
    "pilaf station",
    "rice pilaf station",
    "spanish rice station",
    "cilantro lime rice station",
    "asian rice station",
    "hibachi rice station",
    "stir fry rice station",
)

# ─── 10. PIZZA STATION ───────────────────────────────────────────────────────

add("FoodIconPizza",
    "pizza station",
    "pizza bar",
    "pizza line",
    "pizza of the day",
    "daily pizza",
    "pizza by the slice",
    "pizza slice station",
    "build your own pizza",
    "make your own pizza",
    "personal pizza station",
    "flatbread station",
    "flatbread bar",
    "flatbread line",
    "flatbread pizza station",
    "calzone station",
    "stromboli station",
    "cheese pizza station",
    "pepperoni pizza station",
    "veggie pizza station",
    "margherita pizza station",
    "classic pizza station",
    "hand tossed pizza station",
    "thin crust pizza station",
    "deep dish pizza station",
    "brick oven pizza station",
    "wood fired pizza station",
)

# ─── 11. CHICKEN STATION ─────────────────────────────────────────────────────

add("FoodIconChicken",
    "chicken station",
    "chicken bar",
    "chicken line",
    "chicken of the day",
    "daily chicken",
    "rotisserie chicken station",
    "fried chicken station",
    "grilled chicken station",
    "roasted chicken station",
    "baked chicken station",
    "chicken entree station",
    "chicken and sides station",
    "poultry station",
    "chicken breast station",
    "chicken thigh station",
    "chicken wing station",
    "buffalo chicken station",
    "bbq chicken station",
    "teriyaki chicken station",
    "chicken stir fry station",
    "chicken rice bowl station",
    "chicken and rice station",
    "chicken tikka masala station",
    "chicken marsala station",
    "chicken piccata station",
    "chicken parmesan station",
    "chicken parm station",
)

# ─── 12. BURGER / GRILL STATION ──────────────────────────────────────────────

add("FoodIconBurger",
    "burger station",
    "burger bar",
    "burger line",
    "burger of the day",
    "daily burger",
    "build your own burger",
    "make your own burger",
    "grill station",
    "grill bar",
    "grill line",
    "grilled entrees station",
    "hamburger station",
    "cheeseburger station",
    "veggie burger station",
    "plant based burger station",
    "impossible burger station",
    "beyond burger station",
    "slider station",
    "slider bar",
    "smash burger station",
    "classic burger station",
    "gourmet burger station",
)

# ─── 13. SANDWICH / DELI STATION ─────────────────────────────────────────────

add("FoodIconSandwich",
    "sandwich station",
    "sandwich bar",
    "sandwich line",
    "deli station",
    "deli bar",
    "deli line",
    "deli counter",
    "build your own sandwich",
    "make your own sandwich",
    "sub station",
    "sub bar",
    "sub line",
    "hoagie station",
    "wrap station",
    "wrap bar",
    "wrap line",
    "panini station",
    "panini bar",
    "grilled sandwich station",
    "grilled cheese station",
    "hot sandwich station",
    "cold sandwich station",
    "lunch station",
    "lunch bar",
    "deli sandwich station",
    "fresh sandwich station",
    "made to order sandwich",
    "custom sandwich station",
)

# ─── 14. FISH / SEAFOOD STATION ──────────────────────────────────────────────

add("FoodIconFish",
    "fish station",
    "fish bar",
    "fish line",
    "fish of the day",
    "daily fish",
    "seafood station",
    "seafood bar",
    "seafood line",
    "fish entree station",
    "baked fish station",
    "grilled fish station",
    "fried fish station",
    "salmon station",
    "tuna station",
    "tilapia station",
    "cod station",
    "halibut station",
    "mahi station",
    "mahi mahi station",
    "catfish station",
    "trout station",
    "fish fry station",
    "fish and chips station",
    "fish taco station",
    "seafood entree",
    "catch of the day",
    "fresh catch station",
)

# ─── 15. DESSERT STATION ─────────────────────────────────────────────────────

add("FoodIconCake",
    "dessert station",
    "dessert line",
    "baked goods station",
    "baked goods line",
    "bakery line",
    "cake station",
    "cake bar",
    "cake line",
    "cake of the day",
    "daily cake",
    "fresh baked cake",
    "daily baked goods",
    "fresh baked goods",
    "baked dessert station",
    "baked desserts",
    "daily baked dessert",
)

# ─────────────────────────────────────────────────────────────────────────────

random.shuffle(ADDITIONS)
split = int(len(ADDITIONS) * 0.9)
new_train = ADDITIONS[:split]
new_val   = ADDITIONS[split:]

train_rows.extend(new_train)
val_rows.extend(new_val)

random.shuffle(train_rows)
random.shuffle(val_rows)

save(TRAIN_IN, train_rows)
save(VAL_IN,   val_rows)

from collections import Counter
counts_train = Counter(r["label"] for r in train_rows)

print(f"Total examples : {len(train_rows)+len(val_rows)}")
print(f"Training rows  : {len(train_rows)}")
print(f"Validation rows: {len(val_rows)}")
print(f"New examples   : {len(ADDITIONS)} (+{split} train, +{len(new_val)} val)")
print(f"\nModified classes:")
for k in sorted(set(r["label"] for r in ADDITIONS)):
    print(f"  {k:<45} {counts_train[k]}")
print(f"\nSmallest 10:")
for k,v in sorted(counts_train.items(), key=lambda x: x[1])[:10]:
    print(f"  {k:<45} {v}")
