#!/usr/bin/env python3
"""expand_v4.py — targeted fixes for round 4 misclassifications.

Issues:
1. Cereal Bar → crossed utensils   Fix: remove wrong "cereal bar→Protein", add lots of cereal bar→Wheat
2. Dessert Bar → utensils          Fix: massive expansion of dessert bar→Cake + Dessert
3. Hot Dogs → sandwich             Fix: large expansion of hot dog station examples
4. Taqueria → sandwich             Fix: large expansion of taqueria examples
5. General "bar" word pollution    Fix: add more counter-examples for bar stations
"""

import csv, pathlib, random

ROOT = pathlib.Path(__file__).parent
TRAIN_IN  = ROOT / "training_data.csv"
VAL_IN    = ROOT / "validation_data.csv"

random.seed(101)

def load(path):
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            rows.append({"text": r["text"], "label": r["label"]})
    return rows

def save(path, rows):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["text","label"])
        w.writeheader()
        w.writerows(rows)

train_rows = load(TRAIN_IN)
val_rows   = load(VAL_IN)

# ── Step 1: Remove the wrong "cereal bar → FoodIconProtein" entry ─────────────
train_rows = [r for r in train_rows if not (r["text"] == "cereal bar" and r["label"] == "FoodIconProtein")]
val_rows   = [r for r in val_rows   if not (r["text"] == "cereal bar" and r["label"] == "FoodIconProtein")]

# ── New examples ──────────────────────────────────────────────────────────────
ADDITIONS = []

def add(label, *texts):
    for t in texts:
        ADDITIONS.append({"text": t.strip(), "label": label})

# ─── 1. CEREAL BAR → FoodIconWheat ───────────────────────────────────────────
# "Cereal Bar" as a cafeteria station = breakfast cereal station
add("FoodIconWheat",
    "cereal bar",
    "cereal bar station",
    "cereal bar line",
    "line cereal bar",
    "breakfast cereal bar",
    "build your own cereal",
    "cereal station",
    "cereal line",
    "cereal",
    "cereals",
    "breakfast cereal",
    "breakfast cereals",
    "cold cereal",
    "hot cereal",
    "cereal and milk",
    "cereal with milk",
    "cereal buffet",
    "cereal selection",
    "cereal choices",
    "assorted cereal",
    "assorted cereals",
    "variety cereal",
    "cereal variety",
    "cereal options",
    "daily cereal",
    "morning cereal",
    "build a bowl cereal",
    "cereal bowl station",
    "self serve cereal",
    "grab and go cereal",
    "individual cereal box",
    "mini cereal box",
    "single serve cereal",
    "cereal cup",
    "granola bar",
    "granola bars",
    "cereal granola bar",
    "oat bar",
    "oat bars",
    "nutrigrain bar",
    "nutrigrain",
    "nature valley bar",
    "nature valley",
    "kind bar",
    "kind bars",
    "fiber bar",
    "bran bar",
    "whole grain bar",
    "breakfast bar",
    "breakfast bars",
    "morning bar",
    "oatmeal bar",
    "muesli bar",
    "granola",
    "granola cup",
    "granola bowl",
    "muesli",
    "oatmeal",
    "oatmeal cup",
    "instant oatmeal",
    "cream of wheat",
    "grits",
    "grits station",
    "hot cereal station",
    "oatmeal station",
    "porridge",
    "corn flakes",
    "frosted flakes",
    "lucky charms",
    "cheerios",
    "honey nut cheerios",
    "raisin bran",
    "life cereal",
    "cinnamon toast crunch",
    "froot loops",
    "captain crunch",
    "cocoa puffs",
    "rice krispies",
    "wheaties",
    "grape nuts",
    "mini wheats",
)

# ─── 2. DESSERT BAR → FoodIconCake (massive expansion) ───────────────────────
add("FoodIconCake",
    "dessert bar",
    "dessert bar station",
    "dessert bar line",
    "line dessert bar",
    "dessert bar today",
    "dessert bar daily",
    "dessert bar fresh",
    "dessert bar selections",
    "dessert bar variety",
    "dessert bar options",
    "dessert bar assortment",
    "dessert bar menu",
    "build your own dessert bar",
    "dessert station",
    "dessert line",
    "sweet station",
    "sweets station",
    "sweet bar",
    "sweets bar",
    "sweet treats station",
    "sweet treat bar",
    "baked goods bar",
    "baked goods station",
    "bakery station",
    "bakery bar",
    "pastry station",
    "pastry bar",
    "confections station",
    "confections bar",
    "treat bar",
    "treats station",
    "treats bar",
    "dessert",
    "desserts",
    "daily dessert",
    "featured dessert",
    "dessert of the day",
    "dessert selection",
    "dessert options",
    "assorted desserts",
    "variety desserts",
    "dessert tray",
    "dessert platter",
    "dessert cart",
    "dessert table",
    "cake",
    "cakes",
    "slice of cake",
    "chocolate cake",
    "vanilla cake",
    "birthday cake",
    "sheet cake",
    "layer cake",
    "bundt cake",
    "pound cake",
    "spice cake",
    "carrot cake",
    "lemon cake",
    "red velvet cake",
    "tres leches cake",
    "cheesecake",
    "new york cheesecake",
    "brownie",
    "brownies",
    "chocolate brownie",
    "fudge brownie",
    "blondie",
    "blondies",
    "bar cookie",
    "bar dessert",
    "lemon bar",
    "lemon bars",
    "magic bar",
    "magic bars",
    "seven layer bar",
    "hello dolly bar",
    "cobbler bar",
    "crisp bar",
    "pie bar",
    "fruit bar dessert",
    "sweet bar dessert",
    "cake slice",
    "cake slices",
    "mini cake",
    "cupcake",
    "cupcakes",
    "muffin dessert",
    "danish dessert",
    "pastry dessert",
)

# Also add to FoodIconDessert (the soft-serve swirl icon)
add("FoodIconDessert",
    "soft serve",
    "soft serve station",
    "soft serve bar",
    "soft serve line",
    "ice cream station",
    "ice cream bar",
    "frozen dessert station",
    "frozen dessert bar",
    "frozen dessert line",
    "line frozen dessert",
    "frozen treat station",
    "frozen treat bar",
    "sundae station",
    "sundae bar",
    "build your own sundae",
    "make your own sundae",
    "sundae bar station",
    "topping bar",
    "toppings bar",
    "ice cream topping bar",
    "dessert topping bar",
    "whipped cream station",
    "soft serve dessert",
    "frozen yogurt station",
    "frozen yogurt bar",
    "gelato station",
    "gelato bar",
    "sorbet station",
    "sorbet bar",
)

# ─── 3. HOT DOGS — massive expansion of station-style examples ────────────────
add("FoodIconHotDog",
    "hot dogs",
    "hot dog",
    "hot dog station",
    "hot dogs station",
    "hot dog bar",
    "hot dog line",
    "hot dog stand",
    "build your own hot dog",
    "frank station",
    "franks station",
    "frank line",
    "frank bar",
    "frankfurter station",
    "frankfurter line",
    "sausage station",
    "sausage line",
    "sausage bar",
    "brat station",
    "bratwurst station",
    "corn dog station",
    "corn dog line",
    "corn dog bar",
    "classic hot dog",
    "all beef hot dog",
    "beef frank",
    "beef frankfurter",
    "pork frank",
    "pork dog",
    "turkey dog",
    "chicken dog",
    "coney island",
    "coney station",
    "chili dog",
    "chili cheese dog",
    "chicago dog",
    "chicago style",
    "new york dog",
    "sonoran dog",
    "stadium dog",
    "ballpark frank",
    "ballpark hot dog",
    "jumbo dog",
    "footlong hot dog",
    "foot long dog",
    "mini corn dog",
    "corn dog nuggets",
    "pretzel dog",
    "pretzel wrapped dog",
    "bacon wrapped dog",
    "slaw dog",
    "loaded hot dog",
    "classic frank",
    "plain frank",
    "kielbasa",
    "kielbasa station",
    "polish sausage",
    "polish dog",
    "andouille dog",
    "smoked sausage",
    "smoked frank",
    "weenie",
    "weenies",
    "wiener",
    "wieners",
    "little smokie",
    "little smokies",
    "cocktail weenie",
    "cocktail frank",
    "cocktail sausage",
    "skinless frank",
    "skinless frankfurter",
    "bun length frank",
    "jumbo frank",
    "quarter pound frank",
    "stadium frank",
    "foot long frank",
    "coney frank",
    "grilled hot dog",
    "grilled frank",
    "steamed hot dog",
    "steamed frank",
    "hot dog in bun",
    "frank in bun",
    "sausage in bun",
    "dog in bun",
    "brat in bun",
    "hot dog with bun",
    "frank with bun",
)

# ─── 4. TAQUERIA — large expansion ───────────────────────────────────────────
add("FoodIconTaco",
    "taqueria",
    "taqueria station",
    "taqueria bar",
    "taqueria line",
    "taqueria fresh",
    "fresh taqueria",
    "build a taco",
    "build your own taco",
    "taco bar",
    "taco station",
    "taco line",
    "taco bar station",
    "taco tuesday station",
    "street taco station",
    "street taco bar",
    "street taco line",
    "taco buffet",
    "taco toppings bar",
    "taco fixings station",
    "taco fixings bar",
    "make your own taco",
    "diy taco",
    "taco plate station",
    "taco platter station",
    "mexican station",
    "mexican food station",
    "mexican bar",
    "mexican food bar",
    "mexican food line",
    "mexican line",
    "tex mex station",
    "tex mex bar",
    "tex mex line",
    "tex mex",
    "mexican cuisine station",
    "latin station",
    "latin bar",
    "latina station",
    "south of the border station",
    "taco",
    "tacos",
    "taco platter",
    "taco plate",
    "beef taco",
    "chicken taco",
    "fish taco",
    "shrimp taco",
    "pork taco",
    "carnitas taco",
    "carne asada taco",
    "al pastor taco",
    "barbacoa taco",
    "birria taco",
    "birria",
    "veggie taco",
    "black bean taco",
    "breakfast taco",
    "soft taco",
    "hard taco",
    "crispy taco",
    "street taco",
    "mini taco",
    "taco salad station",
    "taco bowl station",
    "taquito station",
    "taquito bar",
    "rolled taco station",
    "flauta station",
    "nachos station",
    "nachos bar",
    "nachos line",
    "nacho bar",
    "nacho station",
)

# ─── 5. Counter-anchor: reinforce that "X bar" stations are NOT sandwiches ───
# Add general station "bar" examples to correct classes
add("FoodIconSalad",
    "salad bar",
    "salad bar station",
    "salad line",
    "build your own salad",
    "make your own salad",
    "salad station",
    "salad buffet",
    "fresh salad bar",
    "garden salad bar",
    "tossed salad bar",
    "salad bar fresh",
    "salad bar daily",
    "salad toppings bar",
    "veggie bar",
    "vegetable bar",
    "raw bar salad",
)

add("FoodIconSoup",
    "soup bar",
    "soup station",
    "soup line",
    "soup and salad bar",
    "soup bar station",
    "soup bar daily",
    "soup of the day station",
    "daily soup station",
    "hot soup bar",
    "soup and bread station",
    "chili bar",
    "chili station",
    "chili line",
)

add("FoodIconBread",
    "bread bar",
    "bread station",
    "bread line",
    "bagel bar",
    "bagel station",
    "bagel line",
    "toast bar",
    "toast station",
    "biscuit station",
    "biscuit bar",
    "roll station",
    "roll bar",
    "bun station",
    "pastry line",
)

add("FoodIconEgg",
    "egg station",
    "egg bar",
    "egg line",
    "made to order eggs",
    "omelette station",
    "omelette bar",
    "omelet station",
    "omelet bar",
    "omelet line",
    "egg station breakfast",
    "scrambled egg station",
    "fried egg station",
)

# ─────────────────────────────────────────────────────────────────────────────

random.shuffle(ADDITIONS)
split = int(len(ADDITIONS) * 0.9)
new_train = ADDITIONS[:split]
new_val   = ADDITIONS[split:]

train_rows.extend(new_train)
val_rows.extend(new_val)

random.shuffle(train_rows)
random.shuffle(val_rows)

save(TRAIN_IN, train_rows)
save(VAL_IN,   val_rows)

from collections import Counter
counts = Counter(r["label"] for r in train_rows)

print(f"Total examples : {len(train_rows)+len(val_rows)}")
print(f"Training rows  : {len(train_rows)}")
print(f"Validation rows: {len(val_rows)}")
print(f"New examples   : {len(ADDITIONS)} (+{split} train, +{len(new_val)} val)")

print(f"\nModified classes:")
for k in sorted(set(r["label"] for r in ADDITIONS)):
    print(f"  {k:<45} {counts[k]}")

print(f"\nSmallest 10:")
for k,v in sorted(counts.items(), key=lambda x: x[1])[:10]:
    print(f"  {k:<45} {v}")
