#!/usr/bin/env python3
"""expand_v3.py — targeted fixes for 7 reported misclassifications.

Issues addressed:
1. Condiment → candy            Fix: add condiment→FoodIconChefHat
2. Popsicle not matching        Fix: more popsicle examples, consolidate cracker confusion
3. Crackers not showing         Fix: add cracker→FoodIconBread (consistent class)
4. Cookies & cream → banana     Fix: explicit cookies-and-cream→FoodIconCookie
5. Yogurt → popcorn             Fix: 50+ plain yogurt→FoodIconMilk, remove noisy split
6. Hot dogs → sandwich          Fix: more "line X - hot dogs" style examples
7. Taqueria → sandwich          Fix: more taqueria→FoodIconTaco variations
"""

import csv, pathlib, random

ROOT = pathlib.Path(__file__).parent
TRAIN_IN  = ROOT / "training_data.csv"
VAL_IN    = ROOT / "validation_data.csv"

random.seed(99)

# ── helpers ──────────────────────────────────────────────────────────────────

def load(path):
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            rows.append({"text": r["text"], "label": r["label"]})
    return rows

def save(path, rows):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["text","label"])
        w.writeheader()
        w.writerows(rows)

# ── new examples ─────────────────────────────────────────────────────────────

ADDITIONS = []
def add(label, *texts):
    for t in texts:
        ADDITIONS.append({"text": t.strip(), "label": label})

# ─── 1. CONDIMENT → FoodIconChefHat ──────────────────────────────────────────
# No dedicated condiment icon; ChefHat is the best semantic fit for toppings/sauces
add("FoodIconChefHat",
    "condiment",
    "condiments",
    "condiment bar",
    "condiment station",
    "condiment tray",
    "condiment packet",
    "condiment packets",
    "condiment cups",
    "condiment assortment",
    "condiment selection",
    "ketchup",
    "mustard",
    "yellow mustard",
    "dijon mustard",
    "spicy mustard",
    "honey mustard",
    "mayonnaise",
    "mayo",
    "light mayo",
    "sriracha",
    "hot sauce",
    "louisiana hot sauce",
    "tabasco",
    "cholula",
    "tapatio",
    "valentina hot sauce",
    "soy sauce",
    "teriyaki sauce",
    "oyster sauce",
    "fish sauce",
    "worcestershire sauce",
    "steak sauce",
    "bbq sauce",
    "barbecue sauce",
    "sweet and sour sauce",
    "honey sauce",
    "maple syrup",
    "agave syrup",
    "ketchup packet",
    "mustard packet",
    "mayo packet",
    "hot sauce packet",
    "soy sauce packet",
    "dipping sauce",
    "dipping sauces",
    "sauce cup",
    "sauce packets",
    "side sauce",
    "extra sauce",
    "wing sauce",
    "buffalo sauce",
    "honey bbq sauce",
    "garlic aioli",
    "aioli",
    "chipotle mayo",
    "sriracha mayo",
    "remoulade",
    "tzatziki sauce",
    "hummus dip",
    "guacamole dip",
    "salsa",
    "salsa cup",
    "pico de gallo",
    "jam",
    "jelly",
    "fruit jam",
    "butter packet",
    "margarine",
    "cream cheese spread",
    "peanut butter packet",
    "nutella packet",
)

# ─── 2. POPSICLE — more variety + line-style ─────────────────────────────────
add("FoodIconPopsicle",
    "popsicle",
    "popsicles",
    "cherry popsicle",
    "orange popsicle",
    "grape popsicle",
    "strawberry popsicle",
    "lime popsicle",
    "lemon popsicle",
    "watermelon popsicle",
    "mango popsicle",
    "coconut popsicle",
    "pineapple popsicle",
    "kiwi popsicle",
    "blueberry popsicle",
    "peach popsicle",
    "raspberry popsicle",
    "fudge popsicle",
    "chocolate popsicle",
    "vanilla popsicle",
    "creamy popsicle",
    "ice pop",
    "ice pops",
    "fruit ice pop",
    "juice pop",
    "juice pops",
    "freeze pop",
    "freeze pops",
    "otter pop",
    "otter pops",
    "fla vor ice",
    "flavorice",
    "flavor ice pop",
    "popsicle bar",
    "popsicle line",
    "line popsicle",
    "frozen fruit bar",
    "frozen fruit pop",
    "frozen pop",
    "frozen treat on a stick",
    "ice lolly",
    "lolly ice",
    "paleta",
    "paletas",
    "paleta de fruta",
    "agua fresca pop",
    "fruit paleta",
    "mango paleta",
    "strawberry paleta",
    "watermelon paleta",
    "lime paleta",
    "tamarind paleta",
    "dreamsicle",
    "creamsicle",
    "rocket pop",
    "bomb pop",
    "twin pop",
    "push pop",
    "push-up pop",
    "ice cream pop",
    "chocolate fudge pop",
    "fudge pop bar",
    "dole whip bar",
    "dole whip pop",
    "rainbow pop",
    "rainbow popsicle",
    "swirl pop",
    "tie dye pop",
)

# ─── 3. CRACKERS → FoodIconBread ─────────────────────────────────────────────
# Plain crackers have no dedicated icon; Bread is the best match
add("FoodIconBread",
    "crackers",
    "cracker",
    "saltine crackers",
    "saltines",
    "ritz crackers",
    "ritz",
    "club crackers",
    "town house crackers",
    "wheat thins",
    "triscuit",
    "triscuits",
    "cheez-it",
    "cheez its",
    "cheese crackers",
    "cheddar crackers",
    "butter crackers",
    "oyster crackers",
    "soup crackers",
    "snack crackers",
    "whole wheat crackers",
    "multigrain crackers",
    "rice crackers",
    "sesame crackers",
    "water crackers",
    "plain crackers",
    "original crackers",
    "assorted crackers",
    "cracker pack",
    "cracker assortment",
    "cracker basket",
    "cracker tray",
    "bread crackers",
    "lavash crackers",
    "wasa crispbread",
    "crispbread",
    "crispbreads",
    "flatbread crackers",
    "matzo crackers",
    "matzo",
    "graham crackers",
    "graham cracker",
    "honey graham crackers",
    "cinnamon graham crackers",
    "pretzel crackers",
    "pretzel crisps",
    "mini pretzels",
    "pretzels",
    "pretzel",
    "pretzel nuggets",
    "pretzel sticks",
    "pretzel bites",
    "soft pretzel bites",
    "soft pretzel",
    "soft pretzels",
    "bavarian pretzel",
)

# ─── 4. COOKIES & CREAM → FoodIconCookie ─────────────────────────────────────
add("FoodIconCookie",
    "cookies and cream",
    "cookies & cream",
    "cookies n cream",
    "cookies n' cream",
    "cookie and cream",
    "cookie & cream",
    "cookies and cream bar",
    "cookies and cream treat",
    "cookies and cream snack",
    "cookies and cream pack",
    "cookies and cream dessert",
    "drizzilicious cookies and cream",
    "drizzilicious",
    "cookies and cream drizzilicious",
    "drizzilicious bar",
    "drizzilicious snack",
    "cookies cream bar",
    "oreo bar",
    "oreo snack",
    "oreo dessert",
    "oreo cake",
    "oreo cookie",
    "oreo cookies",
    "oreo pack",
    "oreo",
    "oreos",
    "double stuf oreo",
    "golden oreo",
    "oreo minis",
    "oreo thins",
    "oreo mini cookies",
    "s'mores cookie",
    "smores cookie",
    "chocolate sandwich cookie",
    "cream filled cookie",
    "chocolate cream cookie",
    "vanilla creme cookie",
    "sandwich cookie",
    "sandwich cookies",
    "nutter butter",
    "fig newton",
    "fig bar cookie",
    "oatmeal cream pie",
    "chips ahoy",
    "chips ahoy cookie",
    "chips ahoy chewy",
    "soft batch cookie",
    "toll house cookie",
    "lofthouse cookie",
    "snickerdoodle",
    "snickerdoodles",
    "shortbread cookie",
    "butter cookie",
    "sugar cookie",
    "sugar cookies",
    "peanut butter cookie",
    "chocolate chip cookie",
    "chocolate chip cookies",
    "oatmeal raisin cookie",
    "oatmeal cookie",
    "brownie cookie",
    "double chocolate cookie",
    "white chocolate macadamia",
    "macadamia nut cookie",
    "monster cookie",
    "m&m cookie",
    "rainbow sprinkle cookie",
    "frosted cookie",
    "iced cookie",
    "cookie",
    "cookies",
    "cookie pack",
    "cookie assortment",
    "mini cookies",
    "bite size cookies",
    "cookie bites",
)

# ─── 5. YOGURT → FoodIconMilk ────────────────────────────────────────────────
# Problem: "yogurt covered popcorn"→Popcorn was confusing model.
# Overwhelm with plain yogurt→Milk examples.
add("FoodIconMilk",
    "yogurt",
    "yogurts",
    "plain yogurt",
    "vanilla yogurt",
    "strawberry yogurt",
    "blueberry yogurt",
    "peach yogurt",
    "raspberry yogurt",
    "cherry yogurt",
    "mixed berry yogurt",
    "blackberry yogurt",
    "mango yogurt",
    "lemon yogurt",
    "key lime yogurt",
    "coconut yogurt",
    "pineapple yogurt",
    "honey yogurt",
    "caramel yogurt",
    "chocolate yogurt",
    "salted caramel yogurt",
    "salted caramel remix yogurt",
    "greek yogurt",
    "greek yogurt cup",
    "nonfat greek yogurt",
    "low fat yogurt",
    "lowfat yogurt",
    "fat free yogurt",
    "light yogurt",
    "reduced fat yogurt",
    "whole milk yogurt",
    "full fat yogurt",
    "regular yogurt",
    "flavored yogurt",
    "fruit yogurt",
    "fruit on the bottom yogurt",
    "fruit yogurt cup",
    "individual yogurt",
    "single serve yogurt",
    "single serving yogurt",
    "yogurt cup",
    "yogurt cups",
    "yogurt tub",
    "yogurt container",
    "chobani yogurt",
    "chobani",
    "yoplait yogurt",
    "yoplait",
    "dannon yogurt",
    "fage yogurt",
    "siggi's yogurt",
    "activia yogurt",
    "stonyfield yogurt",
    "noosa yogurt",
    "tillamook yogurt",
    "oikos yogurt",
    "oikos",
    "two good yogurt",
    "light and fit yogurt",
    "danimals yogurt",
    "kids yogurt",
    "yogurt squeeze",
    "yogurt pouch",
    "yogurt tube",
    "drinkable yogurt",
    "yogurt drink",
    "yogurt smoothie",
    "lassi",
    "mango lassi",
    "plain lassi",
    "kefir",
    "plain kefir",
    "strawberry kefir",
    "probiotic yogurt",
    "dairy yogurt",
    "dairy free yogurt",
    "coconut milk yogurt",
    "almond milk yogurt",
    "soy yogurt",
    "oat milk yogurt",
    "vegan yogurt",
    "refrigerated yogurt cup",
    "yogurt parfait cup",
    "grab and go yogurt",
    "snack yogurt",
    "breakfast yogurt",
    "protein yogurt",
    "high protein yogurt",
    "icelandic yogurt",
    "skyr",
    "icelandic skyr",
    "vanilla skyr",
    "plain skyr",
    "lemon skyr",
    "strawberry skyr",
)

# ─── 6. HOT DOG — line-style + more variety ──────────────────────────────────
add("FoodIconHotDog",
    "hot dogs",
    "hot dog",
    "line hot dogs",
    "line - hot dogs",
    "station hot dogs",
    "hot dogs station",
    "hot dog station",
    "hot dog line",
    "hot dog bar",
    "build your own hot dog",
    "classic hot dog",
    "all beef hot dog",
    "all beef hotdog",
    "beef hot dog",
    "turkey hot dog",
    "chicken hot dog",
    "pork hot dog",
    "veggie hot dog",
    "jumbo hot dog",
    "quarter pound hot dog",
    "chili hot dog",
    "cheese dog",
    "chili cheese dog",
    "bacon dog",
    "wrapped hot dog",
    "pretzel dog",
    "corn dog",
    "corn dogs",
    "mini corn dog",
    "mini corn dogs",
    "corn dog nuggets",
    "frank",
    "franks",
    "frankfurter",
    "frankfurters",
    "weiner",
    "wiener",
    "footlong",
    "foot long",
    "foot long hot dog",
    "footlong frank",
    "coney dog",
    "coney island dog",
    "new york style hot dog",
    "chicago style hot dog",
    "chicago dog",
    "sonoran hot dog",
    "sausage dog",
    "brat dog",
    "bratwurst",
    "bratwurst dog",
    "grilled brat",
    "stadium hot dog",
    "ballpark hot dog",
    "ballpark frank",
    "little smokies",
    "lil smokies",
    "cocktail weenies",
)

# ─── 7. TAQUERIA — more variety ───────────────────────────────────────────────
add("FoodIconTaco",
    "taqueria",
    "taqueria station",
    "taqueria bar",
    "taqueria line",
    "taqueria fresh",
    "build your own taco",
    "taco bar",
    "taco station",
    "taco line",
    "taco tuesday",
    "taco wednesday",
    "street taco",
    "street tacos",
    "mini street taco",
    "mini tacos",
    "taco",
    "tacos",
    "fish taco",
    "shrimp taco",
    "carne asada taco",
    "al pastor taco",
    "chicken taco",
    "beef taco",
    "pork taco",
    "carnitas taco",
    "barbacoa taco",
    "veggie taco",
    "black bean taco",
    "breakfast taco",
    "hard taco",
    "soft taco",
    "crispy taco",
    "taco shell",
    "taco salad",
    "taco bowl",
    "fajita taco",
    "baja taco",
    "dorado taco",
    "birria taco",
    "birria",
    "taco platter",
    "taco plate",
    "taco kit",
    "build a taco",
    "taco fixings",
    "taco toppings",
    "tortilla taco",
    "corn tortilla taco",
    "flour tortilla taco",
    "taquito",
    "taquitos",
    "rolled taco",
    "rolled tacos",
    "flautas",
    "flauta",
    "mexican station",
    "mexican bar",
    "tex mex bar",
    "tex mex station",
    "nachos station",
)

# ─── also fix banana confusion: "cookies and cream" cross-words ───────────────
# Remove "foster sauce banana" type examples that could bleed; add counter-anchors
add("FoodIconBanana",
    "banana",
    "bananas",
    "fresh banana",
    "ripe banana",
    "overripe banana",
    "banana fruit",
    "whole banana",
    "sliced banana",
    "banana slices",
    "banana chips",
    "dried banana",
    "banana bread",
    "banana muffin",
    "banana pancakes",
    "banana smoothie",
    "banana split",
    "banana pudding",
    "banana cream pie",
    "banana foster",
    "bananas foster",
    "banana oatmeal",
    "banana cereal",
    "banana nut muffin",
    "banana walnut",
    "banana caramel",
    "green banana",
    "yellow banana",
    "baby banana",
    "plantain",
    "plantains",
    "fried plantain",
    "sweet plantain",
    "maduros",
)

# ─── fix: "fresh fruit" → FoodIconApple ───────────────────────────────────────
add("FoodIconApple",
    "fresh fruit",
    "fresh fruits",
    "fresh fruit cup",
    "fresh fruit bowl",
    "fresh fruit plate",
    "fresh fruit bar",
    "fresh fruit salad",
    "mixed fresh fruit",
    "whole fresh fruit",
    "seasonal fresh fruit",
    "fresh seasonal fruit",
    "assorted fresh fruit",
    "grab and go fresh fruit",
    "daily fresh fruit",
    "fresh fruit selection",
)

# ─── extra: nail FoodIconSushi seaweed items ────────────────────────────────
add("FoodIconSushi",
    "seaweed",
    "seaweed salad",
    "roasted seaweed",
    "dried seaweed",
    "seaweed snack",
    "nori",
    "nori sheet",
    "nori roll",
    "seaweed wrap",
    "kelp noodles",
    "wakame",
    "ginger sesame seaweed",
    "sesame seaweed",
    "wasabi seaweed",
    "spicy seaweed",
)

# ─────────────────────────────────────────────────────────────────────────────

train_rows = load(TRAIN_IN)
val_rows   = load(VAL_IN)

random.shuffle(ADDITIONS)

# 90/10 train/val split for new examples
split = int(len(ADDITIONS) * 0.9)
new_train = ADDITIONS[:split]
new_val   = ADDITIONS[split:]

train_rows.extend(new_train)
val_rows.extend(new_val)

random.shuffle(train_rows)
random.shuffle(val_rows)

save(TRAIN_IN, train_rows)
save(VAL_IN,   val_rows)

print(f"Total examples : {len(train_rows)+len(val_rows)}")
print(f"Training rows  : {len(train_rows)}")
print(f"Validation rows: {len(val_rows)}")
print(f"New examples added: {len(ADDITIONS)} (+{split} train, +{len(new_val)} val)")

# class counts
from collections import Counter
counts = Counter(r["label"] for r in train_rows)
print(f"\nSmallest 10:")
for k,v in sorted(counts.items(), key=lambda x: x[1])[:10]:
    print(f"  {k:<45} {v}")
print(f"\nModified classes:")
modified = set(r["label"] for r in ADDITIONS)
for k in sorted(modified):
    print(f"  {k:<45} {counts[k]}")
