#!/usr/bin/env python3
"""
Generates training_data.csv and validation_data.csv for FoodIconClassifier (CoreML).
Each row: text (food name), label (asset name).
Run: python3 generate_training_data.py
"""
import csv
import random

random.seed(42)

# ──────────────────────────────────────────────────────────────────────────────
# Training examples per class. Keys MUST match the asset name in Assets.xcassets.
# ──────────────────────────────────────────────────────────────────────────────
classes: dict[str, list[str]] = {

    "FoodIconApple": [
        "apple","apples","apple slices","green apple","red apple","gala apple",
        "honeycrisp apple","fuji apple","granny smith","pink lady apple",
        "braeburn apple","apple wedges","baked apple","apple crisp","apple chips",
        "dried apple","apple cider donut","candied apple","caramel apple",
        "apple turnover","apple fritter","apple pie filling","apple sauce",
        "applesauce","apple butter","apple ring","apple quarters","jazz apple",
        "cosmic crisp","envy apple","ambrosia apple","cripps pink",
        "golden delicious","mcintosh apple","cortland apple","empire apple",
        "rome apple","winesap","spartan apple","liberty apple","zestar apple",
        "smitten apple","kanzi apple","opal apple","sweetango apple",
        "autumn glory apple","SnapDragon apple","sliced apple","whole apple",
        "small apple","large apple","apple fruit","organic apple","fresh apple",
        "raw apple","apple snack","mini apples","crab apple",
    ],

    "FoodIconBanana": [
        "banana","bananas","yellow banana","ripe banana","green banana",
        "banana slices","sliced banana","banana chips","dried banana",
        "plantain","fried plantain","tostones","banana foster","bananas foster",
        "banana pudding","banana cream","banana smoothie","mini bananas",
        "baby bananas","finger banana","burro banana","red banana","manzano banana",
        "cavendish banana","overripe banana","frozen banana","banana snack",
        "banana fruit","organic banana","fresh banana","whole banana",
    ],

    "FoodIconBean": [
        "black beans","kidney beans","refried beans","chickpeas","lentils",
        "navy beans","pinto beans","garbanzo beans","great northern beans",
        "cannellini beans","fava beans","lima beans","edamame","black eyed peas",
        "split peas","adzuki beans","mung beans","butter beans","white beans",
        "red beans","beans","bean","bean soup","bean dip","bean salad",
        "bean bowl","baked beans","boston baked beans","chili beans",
        "three bean salad","mixed beans","steamed edamame","lentil soup",
        "lentil salad","lentil bowl","lentil curry","dal","dahl","red lentil",
        "green lentil","french lentils","chickpea salad","hummus","falafel",
        "chickpea curry","chana masala","rajma","dal makhani","whole beans",
        "boiled beans","cooked lentils","legumes","legume","pulses",
    ],

    "FoodIconBeef": [
        "steak","beef steak","ribeye","ribeye steak","sirloin","sirloin steak",
        "filet mignon","tenderloin","beef tenderloin","t-bone steak","t bone",
        "strip steak","new york strip","porterhouse","wagyu","wagyu steak",
        "prime rib","beef roast","roast beef","beef brisket","brisket",
        "flat iron steak","hanger steak","skirt steak","flank steak",
        "chuck steak","round steak","beef short ribs","beef ribs","braised beef",
        "grilled steak","pan seared steak","beef medallions","beef filet",
        "beef entrecote","carne asada","steak fajitas","beef fajitas",
        "beef stir fry","beef and broccoli","beef bulgogi","bulgogi",
        "beef shabu shabu","beef sukiyaki","beef tataki","beef carpaccio",
        "steak tartare","beef tartare","beef patty","ground beef","hamburger patty",
        "beef meatballs","beef meatloaf","meatloaf","beef picadillo",
        "beef stew","beef bourguignon","pot roast with beef","yankee pot roast",
        "beef Wellington","beef tenderloin roast","prime rib roast","standing rib",
        "dry aged steak","wet aged steak","medium rare steak","well done steak",
        "cowboy steak","tomahawk steak","smash patty","smashburger patty",
    ],

    "FoodIconBeer": [
        "beer","ale","lager","stout","pilsner","ipa","craft beer","pale ale",
        "amber ale","dark ale","wheat beer","hefeweizen","witbier","belgian ale",
        "sour beer","hard cider","hard seltzer","white claw","truly","bud light",
        "budweiser","coors light","miller lite","corona","modelo","dos equis",
        "heineken","stella artois","guinness","blue moon","sam adams","sierra nevada",
        "new belgium","goose island","dogfish head","lagunitas","stone brewing",
        "draft beer","pint of beer","bottle of beer","can of beer","light beer",
        "dark beer","nitro beer","session beer","double ipa","triple ipa",
        "porter","brown ale","red ale","kolsch","saison","farmhouse ale",
        "imperial stout","oatmeal stout","milk stout","cream ale",
    ],

    "FoodIconBottleWine": [
        "wine bottle","bottle of wine","red wine bottle","white wine bottle",
        "bottle of red","bottle of white","bottle of rose","rose bottle",
        "merlot bottle","cabernet bottle","chardonnay bottle","pinot noir bottle",
        "prosecco bottle","champagne bottle","sparkling wine bottle",
        "sauvignon blanc bottle","riesling bottle","moscato bottle",
        "pinot grigio bottle","grenache bottle","syrah bottle","shiraz bottle",
        "zinfandel bottle","malbec bottle","tempranillo bottle","rioja bottle",
        "burgundy bottle","bordeaux bottle","barolo bottle","chianti bottle",
    ],

    "FoodIconBread": [
        "bread","white bread","whole wheat bread","sourdough loaf","bread loaf",
        "whole grain bread","multigrain bread","rye bread","pumpernickel",
        "ciabatta","focaccia","brioche loaf","challah","pullman loaf",
        "sandwich bread","enriched bread","italian bread","french bread",
        "artisan bread","sourdough bread","rustic bread","country bread",
        "homemade bread","fresh bread","sliced bread","unsliced bread",
        "bread roll","dinner roll","wheat roll","kaiser roll","potato roll",
        "pretzel roll","soft roll","hard roll","garlic bread","garlic loaf",
        "texas toast","hawaiian roll","sweet roll","milk bread","shokupan",
        "pita bread","naan bread","flatbread","lavash","injera","teff bread",
        "cornbread","jalapeño cornbread","skillet cornbread","cornbread muffin",
        "biscuit","buttermilk biscuit","flaky biscuit","drop biscuit",
        "english muffin","thomas english muffin","whole wheat english muffin",
        "bagel","plain bagel","everything bagel","sesame bagel","poppy bagel",
        "onion bagel","cinnamon raisin bagel","asiago bagel","blueberry bagel",
        "scone","blueberry scone","cranberry scone","cream scone","plain scone",
        "baguette","french baguette","sourdough baguette","demi baguette",
    ],

    "FoodIconBurger": [
        "burger","cheeseburger","hamburger","double burger","double cheeseburger",
        "veggie burger","turkey burger","impossible burger","beyond burger",
        "smash burger","smashburger","sliders","mini burgers","bacon cheeseburger",
        "mushroom burger","avocado burger","western burger","bbq burger",
        "teriyaki burger","jalapeño burger","fried egg burger","truffle burger",
        "wagyu burger","black bean burger","lentil burger","portobello burger",
        "bison burger","elk burger","lamb burger","salmon burger","tuna burger",
        "big mac","whopper","quarter pounder","double double","in n out burger",
        "five guys burger","shake shack burger","wendy's burger","mcdonalds burger",
        "animal style","protein style burger","lettuce wrapped burger",
        "double smash","triple patty","stacked burger","loaded burger",
        "green chile burger","nm burger","santa fe burger","california burger",
    ],

    "FoodIconBurrito": [
        "burrito","bean burrito","beef burrito","chicken burrito","pork burrito",
        "breakfast burrito","wet burrito","smothered burrito","green chile burrito",
        "red chile burrito","chimichanga","deep fried burrito","quesadilla",
        "cheese quesadilla","chicken quesadilla","steak quesadilla",
        "bean and cheese burrito","beef and bean burrito","carne asada burrito",
        "al pastor burrito","carnitas burrito","veggie burrito","tofu burrito",
        "super burrito","mission burrito","california burrito","san diego burrito",
        "breakfast quesadilla","quesabirria","birria quesadilla","mulita",
        "suizo","suiza","grande burrito","jumbo burrito","burrito bowl (wrap)",
        "foil wrapped burrito","naked burrito","double wrapped burrito",
        "chipotle burrito","taco bell burrito","del taco burrito",
        "fuzzy's burrito","freebirds burrito","moe's burrito","willy's burrito",
    ],

    "FoodIconCake": [
        "cake","birthday cake","wedding cake","chocolate cake","vanilla cake",
        "red velvet cake","carrot cake","lemon cake","strawberry cake",
        "funfetti cake","marble cake","german chocolate cake","black forest cake",
        "pineapple upside down cake","bundt cake","pound cake","sponge cake",
        "angel food cake","chiffon cake","flourless chocolate cake","opera cake",
        "tres leches","tres leches cake","tiramisu","baked alaska",
        "cheesecake","new york cheesecake","japanese cheesecake","no bake cheesecake",
        "strawberry cheesecake","oreo cheesecake","chocolate cheesecake",
        "cupcake","chocolate cupcake","vanilla cupcake","red velvet cupcake",
        "lemon cupcake","birthday cupcake","sprinkle cupcake","mini cupcake",
        "molten lava cake","lava cake","chocolate lava cake","soufflé cake",
        "mocha cake","espresso cake","coffee cake","crumb cake","streusel cake",
        "cinnamon coffee cake","sheet cake","layer cake","single layer cake",
    ],

    "FoodIconCakeSlice": [
        "cake slice","slice of cake","piece of cake","cheesecake slice",
        "piece of cheesecake","birthday cake slice","chocolate cake slice",
        "red velvet slice","carrot cake slice","layer cake slice",
        "wedding cake slice","pound cake slice","coffee cake slice",
        "lemon cake slice","tiramisu slice","tres leches slice",
        "german chocolate slice","black forest slice","funfetti slice",
        "marble cake slice","bundt cake slice","opera cake slice",
    ],

    "FoodIconCandy": [
        "candy","sweets","hard candy","jolly rancher","lifesavers",
        "gummy bears","gummy worms","gummy candy","swedish fish","sour patch kids",
        "airheads","nerds","smarties","starburst","skittles","m&ms","reese pieces",
        "reeses pieces","hershey kisses","kit kat","twix","snickers","milky way",
        "3 musketeers","butterfinger","baby ruth","whoppers","good and plenty",
        "dots","mike and ike","hot tamales","red hots","runts","gobstoppers",
        "everlasting gobstopper","warheads","toxic waste","sour belts","sour strips",
        "haribo","trolli","albanese","brach's candy","sugar daddy","sugar mama",
        "caramel candy","tootsie roll","tootsie pops","blow pop","dum dum",
        "candy corn","circus peanuts","peach rings","gummy rings","wax lips",
        "candy necklace","fun dip","pixy stix","laffy taffy","salt water taffy",
        "taffy","caramel chew","werther's","werther's original","butterscotch candy",
        "peppermint candy","starlight mint","andes mint","after eight",
        "york peppermint patty","junior mints","rolo","milk duds","jujubes",
        "jujyfruits","now and later","bit o honey","mamba","mentos",
    ],

    "FoodIconCandyCane": [
        "candy cane","candy canes","peppermint stick","striped candy",
        "peppermint candy cane","mini candy cane","giant candy cane",
        "chocolate candy cane","holiday candy cane","christmas candy",
        "peppermint twist","old fashioned peppermint stick",
    ],

    "FoodIconCarrot": [
        "carrot","carrots","baby carrots","carrot sticks","carrot slices",
        "shredded carrot","grated carrot","carrot ribbons","rainbow carrots",
        "purple carrot","yellow carrot","white carrot","whole carrot",
        "peeled carrot","roasted carrot","steamed carrot","glazed carrot",
        "honey glazed carrots","carrot medley","carrot salad","carrot slaw",
        "carrot soup","cream of carrot","carrot ginger soup","carrot juice",
        "carrot chips","carrot fries","oven roasted carrots","carrot dip",
    ],

    "FoodIconChefHat": [
        "chef special","house special","chef's choice","today's special",
        "daily special","special of the day","chef's creation","signature dish",
        "chef's selection","house made","house-made","homemade","from scratch",
        "made in house","made from scratch","artisan","housemade","hand crafted",
        "handcrafted","chef prepared","kitchen special","limited special",
        "seasonal special","rotating special","feature","featured dish",
    ],

    "FoodIconCherry": [
        "cherry","cherries","maraschino cherry","sweet cherry","sour cherry",
        "bing cherry","rainier cherry","black cherry","fresh cherries",
        "dried cherries","tart cherries","morello cherries","cherry fruit",
        "red cherries","dark cherries","pitted cherries","cherry halves",
    ],

    "FoodIconChicken": [
        "chicken breast","grilled chicken breast","baked chicken breast",
        "chicken tenders","chicken tender","chicken strips","chicken strip",
        "chicken nuggets","chicken nugget","popcorn chicken","fried chicken",
        "crispy chicken","breaded chicken","panko chicken","chicken cutlet",
        "chicken katsu","chicken schnitzel","chicken parm","chicken parmesan",
        "chicken parmagiana","rotisserie chicken","roasted chicken","whole chicken",
        "half chicken","grilled chicken","bbq chicken","buffalo chicken",
        "honey chicken","teriyaki chicken","general tso chicken","general tso's",
        "orange chicken","sesame chicken","sweet and sour chicken",
        "sweet chili chicken","lemon chicken","piccata","chicken piccata",
        "chicken marsala","chicken francese","chicken milanese","chicken saltimbocca",
        "chicken thigh","boneless chicken thigh","chicken breast fillet",
        "air fried chicken","chicken wing","chicken wings","wings",
        "buffalo wings","hot wings","honey garlic wings","lemon pepper wings",
        "mango habanero wings","korean wings","soy garlic wings","bbq wings",
        "naked wings","boneless wings","smoked chicken","jerk chicken",
        "chicken shawarma","chicken kebab","chicken tikka","tikka chicken",
        "butter chicken","chicken tikka masala","chicken korma","chicken curry",
        "chicken stir fry","chicken and broccoli","kung pao chicken",
        "moo goo gai pan","chicken lo mein noodles","cashew chicken",
    ],

    "FoodIconCitrus": [
        "orange","oranges","navel orange","blood orange","cara cara orange",
        "valencia orange","mandarin","clementine","tangerine","satsuma",
        "minneola","tangelo","grapefruit","ruby red grapefruit","pink grapefruit",
        "white grapefruit","pomelo","yuzu","kumquat","lemon orange",
        "orange slices","orange segments","peeled orange","fresh orange",
        "citrus fruit","citrus","orange juice fruit","cara cara",
    ],

    "FoodIconCoffee": [
        "coffee","espresso","latte","cappuccino","americano","macchiato",
        "mocha","frappuccino","cold brew","cold brew coffee","cortado",
        "flat white","ristretto","lungo","pour over","drip coffee",
        "black coffee","coffee with milk","coffee with cream","iced coffee",
        "iced latte","iced americano","iced macchiato","vanilla latte",
        "caramel latte","hazelnut latte","pumpkin spice latte","oat milk latte",
        "almond milk latte","soy latte","coconut milk latte","lavender latte",
        "matcha latte","chai latte","dirty chai","starbucks","dunkin","peets",
        "dutch bros","philz coffee","intelligentsia","blue bottle","verve",
        "nitro cold brew","nitro coffee","vietnamese coffee","turkish coffee",
        "cuban coffee","cafe con leche","cafe au lait","café au lait",
        "triple shot espresso","double shot espresso","affogato",
        "espresso tonic","coffee energy drink","coffee protein shake",
    ],

    "FoodIconCookie": [
        "cookie","cookies","chocolate chip cookie","oatmeal cookie",
        "sugar cookie","snickerdoodle","peanut butter cookie","shortbread",
        "butter cookie","linzer cookie","thumbprint cookie","spritz cookie",
        "gingerbread cookie","molasses cookie","biscotti","pizzelle",
        "meringue cookie","macaron","macaroon","coconut macaroon","sandwich cookie",
        "oreo","double stuf oreo","golden oreo","oreo thins","oreo minis",
        "nutter butter","chips ahoy","pepperidge farm","famous amos","tate's",
        "lenny and larry","mrs fields","great american cookies","crumbl cookie",
        "levain bakery cookie","bakery cookie","giant cookie","jumbo cookie",
        "mini cookies","cookie bites","cookie dough","edible cookie dough",
        "oatmeal raisin cookie","white chocolate macadamia","double chocolate",
        "triple chocolate cookie","s'mores cookie","birthday cake cookie",
        "funfetti cookie","red velvet cookie","lemon cookie","almond cookie",
        "fortune cookie","fig newton","animal crackers","graham cracker",
        "chocolate graham cracker","honey graham","cookie thins",
    ],

    "FoodIconCookingPot": [
        "stew","beef stew","lamb stew","pork stew","chicken stew",
        "vegetable stew","irish stew","pot roast","yankee pot roast",
        "dutch oven chicken","braised short ribs","braised lamb","osso buco",
        "coq au vin","beef bourguignon","cassoulet","goulash","hungarian goulash",
        "czech goulash","ragout","ragu","bolognese sauce","meat sauce",
        "chili","beef chili","turkey chili","white chicken chili","vegetarian chili",
        "texas chili","cincinnati chili","green chile stew","posole","pozole",
        "green pozole","red pozole","white pozole","menudo","birria stew",
        "mashed potatoes","instant mashed","mashed potato","smashed potatoes",
        "whipped potatoes","potato puree","scalloped potatoes","au gratin",
        "potato gratin","hash","corned beef hash","chicken hash",
        "slow cooker meal","crockpot meal","pressure cooker meal","instant pot",
        "braised dish","braise","slow cooked","simmered","long cooked",
    ],

    "FoodIconCroissant": [
        "croissant","croissants","butter croissant","plain croissant",
        "almond croissant","chocolate croissant","pain au chocolat",
        "ham and cheese croissant","egg and cheese croissant","croissant sandwich",
        "mini croissant","large croissant","flaky croissant","fresh croissant",
        "baked croissant","french croissant","all butter croissant",
        "whole wheat croissant","multigrain croissant","croissant roll",
        "crescent roll","crescent dough","pillsbury crescent","crescent pastry",
        "danish","cheese danish","fruit danish","cream cheese danish",
        "pain au lait","kouign amann","morning bun","cinnamon morning bun",
        "twist pastry","puff pastry","flaky pastry","layered pastry",
        "palmier","elephant ear pastry","mille feuille","napoleon pastry",
        "pain suisse","pain aux raisins","escargot pastry",
    ],

    "FoodIconCupSoda": [
        "soda","coke","coca cola","pepsi","sprite","mountain dew","dr pepper",
        "diet coke","diet pepsi","diet soda","zero sugar soda","cherry coke",
        "vanilla coke","coke zero","pepsi zero","lemon lime soda","ginger ale",
        "canada dry","schweppes","cream soda","orange soda","fanta","crush",
        "root beer","a&w root beer","barq's root beer","mug root beer",
        "birch beer","grape soda","strawberry soda","watermelon soda",
        "fountain drink","fountain soda","soft drink","carbonated beverage",
        "fizzy drink","lemonade","arnold palmer","half and half","iced tea lemonade",
        "sweet tea","unsweetened iced tea","green tea drink","iced tea",
        "lemon iced tea","peach iced tea","raspberry iced tea","arizona tea",
        "snapple","brisk iced tea","peace tea","liquid death","sparkling water",
        "la croix","bubly","spindrift","waterloo","topo chico","perrier",
        "san pellegrino","club soda","tonic water","sparkling lemonade",
        "flavored sparkling water","energy drink","red bull","monster","bang",
        "celsius","prime","ghost energy","c4 energy","reign energy",
        "powerade","gatorade","vitamin water","coconut water","sports drink",
    ],

    "FoodIconDessert": [
        "soft serve","soft serve ice cream","soft serve cone","swirl ice cream",
        "vanilla swirl","chocolate swirl","twist soft serve","frozen custard",
        "custard cone","culver's custard","shake shack custard","concrete mixer",
        "blizzard","dairy queen blizzard","dq blizzard","mcflurry","shamrock shake",
        "gelato","gelato scoop","stracciatella gelato","pistachio gelato",
        "dessert","sweet dessert","frozen dessert","after dinner dessert",
        "dessert course","sweet course","treat","sweet treat","indulgence",
        "pastry cream","creme brulee","crème brûlée","pot de creme","panna cotta",
        "mousse","chocolate mousse","cream puff","eclair","profiterole",
        "churro","churros","fried ice cream","mochi ice cream","rolled ice cream",
        "nice cream","vegan ice cream","dairy free ice cream","coconut ice cream",
        "sorbet scoop","sherbet","rainbow sherbet","frozen custard scoop",
    ],

    "FoodIconDonut": [
        "donut","doughnut","glazed donut","chocolate donut","old fashioned donut",
        "raised donut","cake donut","yeast donut","bavarian cream donut",
        "boston cream donut","jelly donut","jelly filled donut","apple fritter donut",
        "maple donut","maple frosted","sprinkle donut","rainbow sprinkle donut",
        "cinnamon sugar donut","powdered donut","powdered sugar donut",
        "donut holes","munchkins","timbits","donut bites","mini donuts",
        "long john","bismarck donut","bear claw","twisted donut","cruller",
        "french cruller","old fashioned cruller","glazed cruller","cronut",
        "croughnut","cronuts","cider donut","apple cider donut","pumpkin donut",
        "dunkin donut","krispy kreme","beignet","malasada","pacific donut",
        "portuguese donut","zeppole","sufganiyot","loukoumades","oliebollen",
    ],

    "FoodIconDrumstick": [
        "chicken drumstick","drumstick","chicken leg","chicken legs",
        "chicken quarters","leg quarters","dark meat chicken","bbq drumstick",
        "baked drumstick","roasted drumstick","fried drumstick","smoked drumstick",
        "honey glazed drumstick","garlic drumstick","lemon herb drumstick",
        "teriyaki drumstick","buffalo drumstick","korean drumstick",
        "chicken leg piece","chicken thigh and leg","whole leg","bone-in chicken",
        "bone in leg","bone in thigh","chicken leg quarter","family pack chicken",
        "party wings","drumettes","drumette","chicken drumettes",
        "oven baked chicken legs","chicken legs and thighs","barbecue chicken leg",
        "grilled chicken leg","smoked chicken leg","jerk chicken leg",
        "spicy chicken leg","herb roasted chicken leg","crispy chicken leg",
    ],

    "FoodIconEgg": [
        "egg","eggs","boiled egg","hard boiled egg","soft boiled egg",
        "deviled eggs","deviled egg","pickled egg","scotch egg",
        "jammy egg","marinated egg","ramen egg","soy sauce egg",
        "century egg","preserved egg","salted egg","thousand year egg",
        "egg salad","egg salad sandwich","egg mayo","whole egg","raw egg",
        "organic egg","free range egg","pasture raised egg","brown egg",
        "white egg","jumbo egg","large egg","medium egg","small egg",
        "cracked egg","egg protein","high protein egg","cage free egg",
    ],

    "FoodIconEggFried": [
        "fried egg","sunny side up","over easy","over medium","over hard",
        "basted egg","over easy egg","sunny side up egg","over medium egg",
        "over hard egg","fried egg on toast","egg and toast","breakfast egg",
        "skillet egg","pan fried egg","butter fried egg","olive oil fried egg",
        "cast iron egg","runny egg","crispy fried egg","lacy fried egg",
        "spanish fried egg","huevos fritos","shakshuka","shakshouka",
        "eggs in purgatory","egg in a hole","toad in a hole","cloud egg",
    ],

    "FoodIconFish": [
        "fish","salmon","baked salmon","grilled salmon","pan seared salmon",
        "salmon fillet","atlantic salmon","sockeye salmon","king salmon",
        "coho salmon","smoked salmon","lox","nova lox","gravlax","cured salmon",
        "tuna","tuna steak","ahi tuna","yellowfin tuna","bluefin tuna",
        "albacore tuna","seared tuna","tuna tartare","tuna poke",
        "tilapia","baked tilapia","grilled tilapia","fried tilapia",
        "cod","baked cod","fish and chips cod","atlantic cod","pacific cod",
        "halibut","pacific halibut","atlantic halibut","halibut fillet",
        "mahi mahi","mahi","grilled mahi","sea bass","chilean sea bass",
        "branzino","whole branzino","grilled branzino","trout","rainbow trout",
        "brook trout","lake trout","catfish","fried catfish","bass",
        "striped bass","black bass","largemouth bass","snapper","red snapper",
        "yellowtail snapper","grouper","flounder","sole","dover sole",
        "swordfish","swordfish steak","monkfish","pollock","haddock",
        "mackerel","sardines","anchovies","herring","whitefish",
        "fish fillet","fish dish","baked fish","grilled fish","steamed fish",
        "whole fish","fish entree","seafood fish","white fish",
    ],

    "FoodIconFries": [
        "french fries","fries","steak fries","shoestring fries","curly fries",
        "waffle fries","crinkle cut fries","seasoned fries","garlic fries",
        "parmesan fries","truffle fries","cajun fries","spicy fries",
        "chili cheese fries","loaded fries","disco fries","animal fries",
        "in n out fries","five guys fries","shake shack fries","mcdonalds fries",
        "tater tots","tots","potato tots","crispy tots","cheesy tots",
        "potato wedges","steak wedges","potato skins","potato puffs",
        "poutine","canadian poutine","cheese curds and gravy","fries and gravy",
        "sweet potato fries","yam fries","purple yam fries","zucchini fries",
        "carrot fries","beet fries","rutabaga fries","jicama fries",
        "oven fries","baked fries","air fryer fries","frozen fries",
        "spiral fries","tornado fries","tornado potato","twister fries",
        "smash fries","boardwalk fries","old bay fries","vinegar fries",
    ],

    "FoodIconGlassWater": [
        "water","glass of water","sparkling water","mineral water","seltzer",
        "hydrogen water","still water","iced water","tap water","filtered water",
        "spring water","alkaline water","distilled water","purified water",
        "poland spring","evian","fiji water","voss","smartwater","aquafina",
        "dasani","deer park","ozarka","ice mountain","zephyrhills",
        "hydration","water bottle","drink water","flavored water","infused water",
        "cucumber water","lemon water","watermelon water","mint water",
        "electrolyte water","pedialyte","liquid iv","nuun","trace minerals",
        "water with lemon","water with lime","club soda no flavor",
    ],

    "FoodIconGrape": [
        "grape","grapes","red grapes","green grapes","purple grapes","black grapes",
        "cotton candy grapes","concord grapes","muscat grapes","seedless grapes",
        "table grapes","wine grapes","champagne grapes","thomcord grapes",
        "crimson grapes","autumn royal grapes","sweet grapes","fresh grapes",
        "frozen grapes","grape snack","grape fruit","organic grapes",
        "raisin","raisins","golden raisin","golden raisins","dried grapes",
        "currant","currants","dried currant","black currant","zante currants",
    ],

    "FoodIconHam": [
        "ham","deli ham","honey ham","black forest ham","virginia ham",
        "smithfield ham","spiral ham","glazed ham","prosciutto","prosciutto di parma",
        "prosciutto crudo","serrano ham","iberico ham","jamon iberico","jamon serrano",
        "country ham","city ham","cured ham","smoked ham","baked ham",
        "deli meat","cold cuts","lunch meat","charcuterie","salami","pepperoni",
        "capicola","soppressata","mortadella","bologna","bologna sandwich",
        "liverwurst","head cheese","pastrami","corned beef","roast beef deli",
        "turkey breast deli","turkey deli","chicken deli","smoked turkey",
    ],

    "FoodIconHotDog": [
        "hot dog","hotdog","hot dogs","corn dog","corndog","mini corn dog",
        "frankfurter","frank","franks","red hot","coney island dog","coney dog",
        "chili dog","chili cheese dog","chicago style hot dog","new york dog",
        "seattle dog","sonoran dog","texas hot dog","loaded hot dog",
        "bratwurst","brat","german sausage","beer brat","grilled brat",
        "andouille","andouille sausage","italian sausage","spicy italian sausage",
        "sweet italian sausage","breakfast sausage link","sausage link",
        "pork sausage link","chicken sausage link","turkey sausage link",
        "kielbasa","polish sausage","smoked sausage","chorizo link",
        "merguez","weiner","wienerschnitzel","stadium dog","footlong hot dog",
    ],

    "FoodIconIceCream": [
        "ice cream cone","ice cream","vanilla cone","chocolate cone",
        "strawberry cone","twist cone","dipped cone","chocolate dipped cone",
        "waffle cone","sugar cone","cake cone","wafer cone","junior cone",
        "kiddie cone","small cone","large cone","double scoop cone",
        "triple scoop cone","single scoop cone","ice cream scoop on cone",
        "soft serve cone","vanilla soft serve cone","chocolate soft serve cone",
        "swirl cone","rainbow sherbet cone","sherbet cone","sorbet cone",
        "gelato cone","mochi ice cream cone","levain cone","premium cone",
    ],

    "FoodIconIceCreamBowl": [
        "ice cream sundae","sundae","banana split","ice cream bowl",
        "ice cream cup","scoop of ice cream","two scoops","three scoops",
        "double scoop bowl","triple scoop bowl","ice cream dish","ice cream plate",
        "hot fudge sundae","caramel sundae","strawberry sundae","mint chocolate sundae",
        "cookie dough sundae","brownie sundae","peanut butter sundae",
        "turtle sundae","rocky road sundae","neapolitan bowl",
        "parfait","ice cream parfait","fruit parfait","yogurt parfait",
        "layered dessert","dessert bowl","sweet bowl","frozen yogurt cup",
        "froyo cup","frozen yogurt bowl","acai bowl","dragon fruit bowl",
        "pitaya bowl","smoothie bowl","nice cream bowl",
    ],

    "FoodIconIceCreamSandwich": [
        "ice cream sandwich","ice cream sandwiches","chipwich","cookie ice cream sandwich",
        "brownie ice cream sandwich","ice cream bar","klondike bar","snickers ice cream",
        "twix ice cream","oreo ice cream bar","drumstick ice cream","creamsicle bar",
        "dreamsicle bar","fudgsicle bar","it's it ice cream sandwich",
        "vanilla ice cream sandwich","chocolate ice cream sandwich",
        "neapolitan ice cream sandwich","mint chip ice cream sandwich",
    ],

    "FoodIconLollipop": [
        "lollipop","lollipops","sucker","ring pop","tootsie pop","blow pop",
        "charms blow pop","chupa chups","dum dum","dum dums","flat pop",
        "ribbon candy lollipop","hard candy lollipop","fruit lollipop",
        "watermelon lollipop","cherry lollipop","grape lollipop","sour lollipop",
        "giant lollipop","large lollipop","jumbo lollipop","mini lollipop",
        "chocolate lollipop","swirl lollipop","crystal lollipop","rock candy",
    ],

    "FoodIconMartini": [
        "martini","cocktail","mixed drink","vodka martini","gin martini",
        "dirty martini","dry martini","espresso martini","pornstar martini",
        "cosmopolitan","cosmo","margarita","frozen margarita","skinny margarita",
        "mojito","mango mojito","strawberry mojito","old fashioned","manhattan",
        "negroni","boulevardier","aperol spritz","campari spritz","hugo spritz",
        "daiquiri","frozen daiquiri","strawberry daiquiri","lime daiquiri",
        "moscow mule","dark and stormy","gin and tonic","rum and coke",
        "whiskey sour","amaretto sour","gimlet","southside","last word",
        "clover club","paloma","tequila sunrise","sex on the beach",
        "long island iced tea","pina colada","frozen pina colada","bahama mama",
        "hurricane","blue lagoon","mai tai","zombie","singapore sling",
        "shirley temple","arnold palmer cocktail","sangria","wine spritzer",
        "spritz","prosecco cocktail","mimosa","bellini","kir royale",
    ],

    "FoodIconMicrowave": [
        "microwave meal","microwave dinner","microwaveable","frozen meal",
        "frozen dinner","tv dinner","lean cuisine","healthy choice","weight watchers",
        "smart ones","stouffer's","marie callender's","banquet meal",
        "birds eye meal","green giant meal","amy's frozen","kashi frozen",
        "trader joe's frozen","whole foods frozen meal","freshly meal",
        "factor meal","home chef meal","hello fresh leftovers","meal prep leftovers",
        "reheated meal","leftover pizza","leftover pasta","leftover rice",
        "microwave rice","microwave pasta","microwave popcorn","easy mac",
        "kraft mac and cheese","microwavable","instant meal","quick meal",
        "convenience food","ready meal","prepackaged meal","packaged meal",
    ],

    "FoodIconMilk": [
        "milk","whole milk","skim milk","2% milk","1% milk","fat free milk",
        "reduced fat milk","almond milk","oat milk","soy milk","coconut milk beverage",
        "macadamia milk","cashew milk","rice milk","pea milk","hemp milk",
        "flax milk","lactose free milk","dairy milk","organic milk","raw milk",
        "ultra-pasteurized milk","ultra pasteurized milk","uht milk",
        "buttermilk","kefir","drinkable yogurt","dairy drink","milk drink",
        "chocolate milk","strawberry milk","banana milk","hot chocolate milk",
        "warm milk","cold milk","milk glass","glass of milk","cup of milk",
        "a2 milk","jersey milk","goat milk","sheep milk","buffalo milk",
    ],

    "FoodIconNut": [
        "almonds","cashews","walnuts","pecans","macadamia nuts","pistachios",
        "peanuts","mixed nuts","hazelnuts","brazil nuts","pine nuts","chestnuts",
        "pine nut","pecan","walnut","almond","cashew","macadamia","pistachio",
        "hazelnut","brazil nut","chestnut","trail mix","mixed nut blend",
        "roasted nuts","salted nuts","unsalted nuts","dry roasted almonds",
        "honey roasted peanuts","spiced nuts","candied nuts","praline nuts",
        "nut butter","almond butter","peanut butter","cashew butter",
        "sunflower butter","hazelnut butter","pistachio butter",
        "nut mix","snack nuts","bar nuts","cocktail nuts","nut snack",
        "nutella","peanut butter and jelly","pb&j","peanut butter crackers",
    ],

    "FoodIconPasta": [
        "pasta","spaghetti","penne","fettuccine","linguine","rigatoni",
        "fusilli","rotini","farfalle","bow tie pasta","cavatappi","ziti",
        "macaroni","elbow macaroni","mac and cheese","kraft macaroni",
        "baked mac and cheese","lobster mac","truffle mac","white cheddar mac",
        "lasagna","baked lasagna","vegetable lasagna","meat lasagna","cheese lasagna",
        "ravioli","cheese ravioli","beef ravioli","butternut squash ravioli",
        "mushroom ravioli","lobster ravioli","crab ravioli","spinach ravioli",
        "tortellini","cheese tortellini","meat tortellini","tortelloni",
        "gnocchi","potato gnocchi","ricotta gnocchi","pumpkin gnocchi",
        "orecchiette","paccheri","bucatini","spaghettini","capellini","angel hair",
        "vermicelli","orzo","acini di pepe","couscous","pearl couscous","israeli couscous",
        "pasta salad","pasta primavera","pasta carbonara","carbonara","cacio e pepe",
        "pasta amatriciana","pasta arrabbiata","pasta aglio e olio","cacio e pepe",
        "pasta bolognese","pasta marinara","spaghetti marinara","pasta pomodoro",
        "pasta with meatballs","spaghetti and meatballs","pasta fagioli",
        "baked ziti","stuffed shells","pasta e fagioli","pasta soup",
        "cold pasta","pasta dish","italian pasta","fresh pasta","dried pasta",
    ],

    "FoodIconPizza": [
        "pizza","pepperoni pizza","cheese pizza","margherita pizza",
        "sausage pizza","supreme pizza","hawaiian pizza","veggie pizza",
        "meat lovers pizza","four cheese pizza","bbq chicken pizza",
        "buffalo chicken pizza","white pizza","pizza bianca","clam pizza",
        "shrimp pizza","lobster pizza","artichoke pizza","fig pizza",
        "prosciutto pizza","truffle pizza","mushroom pizza","spinach pizza",
        "pesto pizza","chicken pesto pizza","bruschetta pizza",
        "deep dish pizza","chicago deep dish","pan pizza","detroit style pizza",
        "new york style pizza","neapolitan pizza","thin crust pizza",
        "cauliflower crust pizza","gluten free pizza crust","stuffed crust pizza",
        "hand tossed pizza","flatbread pizza","personal pizza","mini pizza",
        "calzone","stromboli","pizza roll","pizza pocket","hot pocket",
        "papa johns","pizza hut","dominos","little caesars","costco pizza",
        "sbarro","jets pizza","blaze pizza","mod pizza","urban bricks",
        "digiorno","tombstone pizza","red baron","totinos","bagel bites",
        "english muffin pizza","naan pizza","pita pizza","lavash pizza",
        "pizza slice","slice of pizza","one slice","two slices",
    ],

    "FoodIconPopcorn": [
        "popcorn","movie popcorn","kettle corn","caramel popcorn","buttered popcorn",
        "smartfood","cheddar popcorn","white cheddar popcorn","cheese popcorn",
        "chicago mix popcorn","chicago style popcorn","garrett popcorn",
        "caramel corn","caramel popcorn ball","popcorn ball","candy corn popcorn",
        "halloween popcorn","movie theater popcorn","large popcorn bucket",
        "medium popcorn","small popcorn","popcorn bag","microwave popcorn",
        "act ii popcorn","orville redenbacher","pop secret","jolly time",
        "skinny pop","boomchickapop","lesser evil popcorn","angie's popcorn",
        "popcorn snack","air popped popcorn","oil popped popcorn",
        "sweet popcorn","savory popcorn","spicy popcorn","ranch popcorn",
        "bacon popcorn","sriracha popcorn","truffle popcorn","parmesan popcorn",
        "birthday cake popcorn","kettle cooked popcorn","organic popcorn",
    ],

    "FoodIconPopsicle": [
        "popsicle","popsicles","ice pop","ice pops","fudgsicle","creamsicle",
        "dreamsicle","otter pop","freezer pop","freeze pop","kool pop",
        "fudge pop","fudge pops","pudding pop","jello pop","rocket pop",
        "bomb pop","twin pop","paleta","fruit paleta","agua fresca bar",
        "mexican popsicle","coconut paleta","mango paleta","tamarind paleta",
        "strawberry paleta","watermelon paleta","lime paleta","hibiscus paleta",
        "horchata paleta","chocolate paleta","cajeta paleta","chamoy paleta",
        "fruit bar","frozen fruit bar","real fruit bar","dole whip bar",
        "outshine bar","fruit and cream bar","push pop","push up pop",
        "orange creamsicle","lime creamsicle","raspberry creamsicle",
        "strawberry ice pop","mango ice pop","peach ice pop","grape ice pop",
        "rainbow ice pop","tie dye ice pop","swirl ice pop",
    ],

    "FoodIconPork": [
        "pork","pork chop","pork chops","bone-in pork chop","boneless pork chop",
        "pork tenderloin","pork loin","pork loin roast","pork shoulder","boston butt",
        "pork belly","pork ribs","baby back ribs","spare ribs","st louis ribs",
        "pork roast","smoked pork","pulled pork","pulled pork sandwich",
        "carnitas","al pastor pork","cochinita pibil","lechon","pernil",
        "char siu","chinese bbq pork","hong shao rou","red braised pork",
        "pork belly bao","pork bao","roast pork","porchetta","porketta",
        "crown roast of pork","rack of pork","pork jowl","pork hock",
        "pork shank","braised pork shank","slow roasted pork","whole roasted pig",
        "suckling pig","roasted whole pig","pig roast","luau pig",
        "ground pork","pork meatballs","pork gyoza","pork dumpling",
        "siu mai","char siu bao","tonkatsu","pork katsu","pork schnitzel",
        "pork piccata","pork marsala","pork medallions","pork scallopini",
    ],

    "FoodIconProtein": [
        "protein bar","protein bars","quest bar","rxbar","clif bar","lara bar",
        "kind bar","built bar","one bar","fulfil bar","grenade bar","fitjoy bar",
        "no cow bar","kirkland protein bar","costco protein bar","premier protein",
        "pure protein bar","power bar","luna bar","think thin bar","think bar",
        "protein shake","protein smoothie","whey protein shake","casein shake",
        "meal replacement shake","protein drink","ready to drink protein",
        "ensure protein","boost protein","muscle milk","premier protein shake",
        "fairlife protein shake","core power","iconic protein","koia",
        "protein powder","whey protein powder","casein protein","plant protein",
        "pea protein","soy protein","hemp protein","mass gainer","weight gainer",
        "pre-workout","pre workout","bcaa","eaa","creatine","amino acids",
        "energy bar","granola bar","clif shot","gu energy","larabar",
        "rxbar","perfect bar","gomacro bar","nakd bar","raw bar",
        "beef jerky bar","meat bar","epic bar","chomps","paleovalley bar",
        "nutrition bar","cereal bar","breakfast bar","snack bar","fiber bar",
        "fiber one bar","nature valley bar","kashi bar","Special K bar",
    ],

    "FoodIconRamen": [
        "ramen","ramen bowl","tonkotsu ramen","shoyu ramen","miso ramen",
        "shio ramen","spicy ramen","tan tan men","tantanmen","mazemen",
        "tsukemen","dry ramen","chicken ramen","pork ramen","seafood ramen",
        "vegan ramen","vegetarian ramen","instant ramen","cup noodles",
        "maruchan","shin ramyun","samyang ramen","buldak noodles","fire noodles",
        "pho","beef pho","chicken pho","vegetarian pho","pho bo","pho ga",
        "pho tai","pho with brisket","pho broth","pho noodles",
        "udon","kake udon","zaru udon","curry udon","kitsune udon","nabeyaki udon",
        "lo mein","chicken lo mein","shrimp lo mein","beef lo mein","vegetable lo mein",
        "pad thai","chicken pad thai","shrimp pad thai","tofu pad thai",
        "chow mein","chicken chow mein","beef chow mein","vegetable chow mein",
        "yakisoba","chicken yakisoba","pork yakisoba","vegetable yakisoba",
        "soba","cold soba","zaru soba","hot soba","kake soba","tempura soba",
        "laksa","curry laksa","asam laksa","penang laksa","singaporean laksa",
        "dan dan noodles","dan dan mian","spicy noodles","noodle bowl",
        "noodle soup","asian noodles","glass noodles","rice noodles",
        "vermicelli noodles","rice vermicelli","banh mi bowl noodles",
    ],

    "FoodIconRefrigerator": [
        "refrigerator","fridge","leftovers","food storage","stored food",
        "chilled food","refrigerated food","cold storage","food prep","meal prep stored",
    ],

    "FoodIconRiceBowl": [
        "rice","white rice","brown rice","jasmine rice","basmati rice",
        "short grain rice","long grain rice","sushi rice","sticky rice",
        "glutinous rice","black rice","red rice","wild rice","forbidden rice",
        "cauliflower rice","fried rice","chicken fried rice","shrimp fried rice",
        "pork fried rice","vegetable fried rice","kimchi fried rice",
        "yangzhou fried rice","egg fried rice","thai fried rice","spam fried rice",
        "rice bowl","donburi","gyudon","oyakodon","katsudon","teriyaki bowl",
        "chicken rice bowl","salmon rice bowl","tuna rice bowl","beef rice bowl",
        "bibimbap","dolsot bibimbap","bibim bap","korean rice bowl",
        "hainanese chicken rice","nasi goreng","nasi lemak","sinangag",
        "garlic rice","cilantro lime rice","spanish rice","mexican rice",
        "arroz con pollo rice","yellow rice","saffron rice","pilaf","rice pilaf",
        "seasoned rice","dirty rice","red beans and rice","rice and beans",
        "congee","jook","rice porridge","okayu","zhou","arroz caldo",
        "rice cake","tteok","mochi rice cake","rice crispy","puffed rice",
        "rice cracker","senbei","onigiri","rice ball","musubi","spam musubi",
        "chirashi","chirashi bowl","poke bowl","poké","ahi poke bowl",
        "salmon poke","tuna poke","shrimp poke","vegan poke bowl",
        "grain bowl","farro bowl","quinoa bowl","ancient grain bowl",
    ],

    "FoodIconSalad": [
        "salad","caesar salad","garden salad","mixed greens","spring mix",
        "cobb salad","greek salad","house salad","side salad","dinner salad",
        "nicoise salad","niçoise salad","wedge salad","iceberg wedge",
        "spinach salad","arugula salad","kale salad","romaine salad",
        "butter lettuce salad","endive salad","watercress salad","frisee salad",
        "caprese salad","tomato mozzarella salad","insalata caprese",
        "panzanella","fattoush","tabbouleh","tabouli","shirazi salad",
        "israeli salad","middle eastern salad","horiatiki","mediterranean salad",
        "pasta salad","macaroni salad","tortellini salad","orzo salad",
        "grain salad","farro salad","quinoa salad","lentil salad","chickpea salad",
        "bean salad","three bean salad","black bean salad","white bean salad",
        "beet salad","roasted beet salad","goat cheese salad","walnut salad",
        "asian salad","thai salad","mango salad","papaya salad","som tum",
        "vietnamese salad","goi ga","goi cuon salad","cold noodle salad",
        "chicken salad","tuna salad","egg salad","crab salad","lobster salad",
        "shrimp salad","seafood salad","steak salad","southwest salad",
        "bbq chicken salad","chef salad","antipasto salad","italian salad",
    ],

    "FoodIconSandwich": [
        "sandwich","sub sandwich","hoagie","hero","grinder","club sandwich",
        "blt","bacon lettuce tomato","turkey sandwich","ham sandwich",
        "roast beef sandwich","tuna sandwich","chicken sandwich","egg salad sandwich",
        "grilled cheese","grilled cheese sandwich","melt","patty melt",
        "panini","pressed sandwich","cuban sandwich","cubano","medianoche",
        "po boy","po'boy","oyster po boy","shrimp po boy","catfish po boy",
        "reuben","corned beef reuben","rachel sandwich","turkey reuben",
        "french dip","beef dip","au jus sandwich","philly cheesesteak",
        "cheesesteak","steak and cheese","whiz wit","wiz wit",
        "italian beef","chicago italian beef","muffuletta","new orleans sandwich",
        "lobster roll","lobster salad roll","new england lobster roll",
        "connecticut lobster roll","crab roll","shrimp roll","lobster bun",
        "banh mi","vietnamese sandwich","banh mi sandwich","pate banh mi",
        "torta","mexican torta","torta ahogada","cemita","molletes",
        "croque monsieur","croque madame","croque","pan bagnat",
        "bocadillo","bocadillo de tortilla","pincho","pintxo",
        "dagwood sandwich","triple decker sandwich","double decker sandwich",
        "open faced sandwich","tartine","smørrebrød","smorrebrod",
        "breakfast sandwich","egg sandwich","bacon egg cheese","sausage egg cheese",
        "mcmuffin","egg mcmuffin","sourdough breakfast sandwich",
    ],

    "FoodIconShoppingBasket": [
        "groceries","grocery","grocery shopping","food shopping","market items",
        "food items","general food","misc food","random food","variety of foods",
        "assorted foods","mixed foods","food selection","weekly groceries",
        "pantry staples","pantry items","staples","bulk food","bulk items",
    ],

    "FoodIconShrimp": [
        "shrimp","prawns","shrimp cocktail","shrimp ring","tiger shrimp",
        "jumbo shrimp","colossal shrimp","large shrimp","medium shrimp",
        "small shrimp","shrimp scampi","garlic shrimp","lemon shrimp",
        "grilled shrimp","fried shrimp","battered shrimp","breaded shrimp",
        "coconut shrimp","popcorn shrimp","shrimp tempura","tempura shrimp",
        "shrimp skewer","shrimp kebab","shrimp and grits","cajun shrimp",
        "shrimp creole","shrimp etouffee","shrimp bisque","shrimp boil",
        "low country boil","shrimp po boy","shrimp tacos","shrimp fajitas",
        "shrimp fried rice","shrimp lo mein","shrimp pad thai","shrimp pho",
        "shrimp curry","butter shrimp","spicy shrimp","honey shrimp",
        "teriyaki shrimp","salt and pepper shrimp","garlic butter shrimp",
    ],

    "FoodIconSnail": [
        "escargot","snail","snails","baked escargot","escargot de bourgogne",
        "snail dish","french escargot","garlic butter snails","herbed snails",
        "snail appetizer","land snail","sea snail","abalone",
        "periwinkle","conch","conch fritters","conch salad","whelk",
    ],

    "FoodIconSoup": [
        "soup","chicken soup","chicken noodle soup","tomato soup","vegetable soup",
        "minestrone","beef soup","beef vegetable soup","clam chowder",
        "new england clam chowder","manhattan clam chowder","corn chowder",
        "potato soup","loaded potato soup","french onion soup","onion soup",
        "bisque","lobster bisque","crab bisque","shrimp bisque","tomato bisque",
        "lentil soup","split pea soup","white bean soup","black bean soup",
        "gazpacho","cold soup","vichyssoise","cucumber soup","avocado soup",
        "miso soup","dashi soup","korean doenjang jjigae","sundubu jjigae",
        "kimchi soup","kimchi jjigae","budae jjigae","army stew",
        "hot and sour soup","egg drop soup","wonton soup","winter melon soup",
        "borscht","borsch","ukrainian borscht","cold borscht","beet soup",
        "mulligatawny","curry soup","thai soup","tom yum","tom kha","thai coconut soup",
        "pumpkin soup","butternut squash soup","carrot soup","broccoli soup",
        "broccoli cheddar soup","cauliflower soup","celery root soup",
        "seafood soup","fish soup","bouillabaisse","cioppino","zarzuela",
        "ramen broth","pho broth","bone broth","chicken broth","beef broth",
        "vegetable broth","stock","soup stock","consommé","clear soup",
        "cream soup","cream of mushroom","cream of tomato","cream of asparagus",
        "thai tom yum","chinese hot pot","shabu shabu broth","sukiyaki broth",
    ],

    "FoodIconSushi": [
        "sushi","sashimi","maki","nigiri","temaki","hand roll","uramaki",
        "inside out roll","california roll","spicy tuna roll","dragon roll",
        "rainbow roll","caterpillar roll","tiger roll","volcano roll",
        "spider roll","shrimp tempura roll","salmon avocado roll",
        "tuna avocado roll","yellowtail roll","hamachi roll","scallop roll",
        "eel roll","unagi roll","crunchy roll","baked sushi","oven baked roll",
        "salmon nigiri","tuna nigiri","shrimp nigiri","yellowtail nigiri",
        "scallop nigiri","eel nigiri","crab nigiri","octopus nigiri",
        "salmon sashimi","tuna sashimi","yellowtail sashimi","halibut sashimi",
        "sushi platter","sushi boat","omakase","chef's selection sushi",
        "sushi burrito","sushirrito","sushi pizza","sushi bake","sushi donut",
        "bento sushi","sushi box","family sushi pack","party tray sushi",
        "salmon roe","ikura","tobiko","masago","caviar sushi",
    ],

    "FoodIconTaco": [
        "taco","tacos","street taco","fish taco","shrimp taco","chicken taco",
        "beef taco","pork taco","carnitas taco","al pastor taco","birria taco",
        "birria","quesabirria","carne asada taco","lengua taco","suadero taco",
        "tripe taco","barbacoa taco","cabeza taco","chicharron taco",
        "vegetarian taco","bean taco","potato taco","mushroom taco",
        "hard shell taco","soft taco","crunchy taco","double decker taco",
        "taco bell taco","taco time taco","del taco","jack in the box taco",
        "taqueria","taqueria menu","taco truck","taco stand",
        "nachos","loaded nachos","nachos supreme","nachos with cheese",
        "cheese nachos","bean and cheese nachos","chicken nachos",
        "beef nachos","guacamole nachos","jalapeno nachos","street nachos",
        "tamale","tamales","red chile tamale","green chile tamale","pork tamale",
        "chicken tamale","cheese tamale","sweet tamale","tamale pie",
        "enchilada","enchiladas","chicken enchilada","beef enchilada",
        "cheese enchilada","verde enchilada","rojo enchilada","suiza enchilada",
        "enchilada plate","enchilada combo","stacked enchilada",
        "tostada","tostadas","bean tostada","carne tostada","chicken tostada",
        "sope","sopes","huarache","gordita","chalupa","tlayuda",
    ],

    "FoodIconUtensils": [
        "meal","food","entrée","entree","main course","main dish","dinner",
        "lunch","breakfast","plate","dish","item","menu item","food item",
        "eating","dining","cuisine","course","serving","portion",
    ],

    "FoodIconUtensilsCrossed": [
        "restaurant","diner","cafe","bistro","eatery","food establishment",
        "dining room","dining experience","fine dining","casual dining",
        "fast casual","quick service","food service","buffet",
    ],

    "FoodIconVegan": [
        "vegan","plant-based","plant based","vegetarian","whole plant food",
        "vegan meal","vegan dish","plant based meal","vegan protein","vegan bowl",
        "vegan entree","vegan option","vegan plate","vegan food","veggie meal",
        "tofu","tofu scramble","silken tofu","firm tofu","extra firm tofu",
        "baked tofu","fried tofu","crispy tofu","tofu stir fry","tofu bowl",
        "tempeh","tempeh stir fry","tempeh bowl","marinated tempeh","grilled tempeh",
        "seitan","wheat gluten","seitan steak","seitan roast","seitan strips",
        "jackfruit","pulled jackfruit","jackfruit tacos","jackfruit carnitas",
        "impossible meat","beyond meat","gardein","tofurky","lightlife",
        "meatless","meat free","vegetable dish","veggie dish","garden dish",
        "veggie bowl","vegetable bowl","mixed vegetable","roasted vegetable",
        "steamed vegetable","sauteed vegetables","stir fry vegetable",
        "buddha bowl","zen bowl","nourish bowl","power bowl vegan",
        "raw food","raw vegan","raw vegetables","salad vegan","green bowl",
    ],

    "FoodIconWheat": [
        "cereal","oatmeal","oats","rolled oats","steel cut oats","quick oats",
        "instant oatmeal","overnight oats","granola","homemade granola",
        "honey granola","maple granola","granola clusters","muesli","bircher muesli",
        "grits","corn grits","stone ground grits","cheesy grits","shrimp and grits",
        "cream of wheat","farina","malt o meal","hot cereal","porridge",
        "corn flakes","frosted flakes","raisin bran","bran flakes","all bran",
        "cheerios","honey nut cheerios","frosted mini wheats","shredded wheat",
        "wheaties","total cereal","grape nuts","product 19","special k cereal",
        "lucky charms","cocoa puffs","froot loops","captain crunch","rice krispies",
        "wheat germ","bran","wheat bran","oat bran","fiber cereal",
        "farro","spelt","kamut","einkorn","emmer wheat","durum wheat",
        "bulgur","bulgur wheat","tabbouleh grain","cracked wheat","wheat berry",
        "barley","pearl barley","pot barley","barley soup","barley salad",
        "quinoa","red quinoa","black quinoa","tri color quinoa","quinoa flakes",
        "amaranth","buckwheat","sorghum","millet","teff grain","grain bowl",
    ],

    "FoodIconWine": [
        "wine","red wine","white wine","glass of wine","wine glass",
        "merlot","cabernet sauvignon","cabernet","pinot noir","syrah","shiraz",
        "zinfandel","malbec","tempranillo","grenache","sangiovese",
        "chardonnay","sauvignon blanc","pinot grigio","pinot gris","riesling",
        "moscato","muscat","gewurztraminer","viognier","albarino","gruner veltliner",
        "rose wine","rosé","provence rose","dry rose","white zinfandel",
        "prosecco","champagne","cava","cremant","sparkling wine",
        "moscato d'asti","lambrusco","brachetto","frizzante",
        "port wine","port","sherry","madeira","marsala wine","vermouth",
        "orange wine","natural wine","biodynamic wine","organic wine",
        "boxed wine","wine in a box","franzia","black box wine",
        "wine spritzer","sangria","mulled wine","glühwein","kir","kir royale",
    ],

    "FoodIconWrap": [
        "wrap","chicken wrap","turkey wrap","veggie wrap","roast beef wrap",
        "tuna wrap","egg salad wrap","caesar salad wrap","buffalo chicken wrap",
        "greek wrap","mediterranean wrap","southwest wrap","bbq wrap",
        "gyro","chicken gyro","pork gyro","lamb gyro","beef gyro","falafel gyro",
        "shawarma","chicken shawarma","beef shawarma","lamb shawarma",
        "mixed shawarma","shawarma plate","shawarma platter",
        "falafel wrap","falafel pita","falafel sandwich","falafel plate",
        "kebab wrap","shish kebab wrap","doner kebab","doner wrap",
        "kofta wrap","souvlaki wrap","gyros pita","pita wrap",
        "lavash wrap","flour tortilla wrap","spinach wrap","tomato wrap",
        "whole wheat wrap","gluten free wrap","low carb wrap","lettuce wrap",
        "collard wrap","rice paper roll","spring roll wrapped","fresh roll",
        "vietnamese spring roll","summer roll","fresh spring roll",
        "burrito style wrap","mission style wrap","foil wrap","naked wrap",
    ],
}

# ──────────────────────────────────────────────────────────────────────────────
# Build dataset
# ──────────────────────────────────────────────────────────────────────────────
all_rows: list[tuple[str, str]] = []
for label, examples in classes.items():
    for text in examples:
        all_rows.append((text.strip(), label))

random.shuffle(all_rows)

# 85/15 train/validation split
split = int(len(all_rows) * 0.85)
train_rows = all_rows[:split]
val_rows = all_rows[split:]

def write_csv(path: str, rows: list[tuple[str, str]]) -> None:
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["text", "label"])
        writer.writerows(rows)

import os
os.makedirs("ml_training", exist_ok=True)
write_csv("ml_training/training_data.csv", train_rows)
write_csv("ml_training/validation_data.csv", val_rows)

print(f"Total examples : {len(all_rows)}")
print(f"Training rows  : {len(train_rows)}")
print(f"Validation rows: {len(val_rows)}")
print(f"Classes        : {len(classes)}")
for label, examples in sorted(classes.items()):
    print(f"  {label:35s} {len(examples):4d} examples")
